// common farming nodes
const Nodes = [
{"id":1, "name":"Preliminaries: Club - Merciless! EMPIRE {<a href= \"https://fategrandorder.fandom.com/wiki/Battle_in_New_York_2018#Club\">wiki</a>}",
"enemy1HP":11077, "enemy1Class":"Assassin", "enemy1Attribute":"Earth", "enemy2HP":16712, "enemy2Class":"Assassin", "enemy2Attribute":"Earth", "enemy3HP":13013, "enemy3Class":"Assassin", "enemy3Attribute":"Earth",
"enemy4HP":22242, "enemy4Class":"Assassin", "enemy4Attribute":"Earth", "enemy5HP":31278, "enemy5Class":"Assassin", "enemy5Attribute":"Earth","enemy6HP":0, "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":39865, "enemy7Class":"Assassin", "enemy7Attribute":"Man", "enemy8HP": 72990, "enemy8Class":"Assassin", "enemy8Attribute":"Earth","enemy9HP":0, "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":2, "name":"Preliminaries: Gym - NY Defense Regiment {<a href= \"https://fategrandorder.fandom.com/wiki/Battle_in_New_York_2018#Gym\">wiki</a>}",
"enemy1HP":12820, "enemy1Class":"Archer", "enemy1Attribute":"Man", "enemy2HP":13798, "enemy2Class":"Archer", "enemy2Attribute":"Man", "enemy3HP":23823, "enemy3Class":"Archer", "enemy3Attribute":"Man",
"enemy4HP":16623, "enemy4Class":"Archer", "enemy4Attribute":"Man", "enemy5HP":51944, "enemy5Class":"Saber", "enemy5Attribute":"Earth", "enemy6HP":29118, "enemy6Class":"Archer", "enemy6Attribute":"Man",
"enemy7HP":100527, "enemy7Class":"Archer", "enemy7Attribute":"Earth", "enemy8HP":59144, "enemy8Class":"Saber", "enemy8Attribute":"Earth", "enemy9HP":0, "enemy9Class":"Saber", "enemy9Attribute":"Man",},
{"id":3, "name":"Preliminaries: Arena - Carnegie Hall {<a href= \"https://fategrandorder.fandom.com/wiki/Battle_in_New_York_2018#Arena\">wiki</a>}",
"enemy1HP":13336, "enemy1Class":"Caster", "enemy1Attribute":"Sky", "enemy2HP":21718, "enemy2Class":"Caster", "enemy2Attribute":"Sky", "enemy3HP":14253, "enemy3Class":"Caster", "enemy3Attribute":"Sky",
"enemy4HP":17647, "enemy4Class":"Caster", "enemy4Attribute":"Sky", "enemy5HP":25646, "enemy5Class":"Caster", "enemy5Attribute":"Sky", "enemy6HP":73810, "enemy6Class":"Caster", "enemy6Attribute":"Earth",
"enemy7HP":152140 , "enemy7Class":"Caster", "enemy7Attribute":"Star", "enemy8HP":81581, "enemy8Class":"Avenger", "enemy8Attribute":"Earth", "enemy9HP":0, "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":4, "name":"Preliminaries: Garden - KAISER FIGHT {<a href= \"https://fategrandorder.fandom.com/wiki/Battle_in_New_York_2018#Garden\">wiki</a>}",
"enemy1HP":16197 , "enemy1Class":"Lancer", "enemy1Attribute":"Man", "enemy2HP":16715, "enemy2Class":"Lancer", "enemy2Attribute":"Man", "enemy3HP":20889, "enemy3Class":"Berserker", "enemy3Attribute":"Man",
"enemy4HP":23152 , "enemy4Class":"Berserker", "enemy4Attribute":"Man", "enemy5HP":18818 , "enemy5Class":"Lancer", "enemy5Attribute":"Man", "enemy6HP":85591, "enemy6Class":"Lancer", "enemy6Attribute":"Earth",
"enemy7HP":104515 , "enemy7Class":"Berserker", "enemy7Attribute":"Man", "enemy8HP":165037 , "enemy8Class":"Lancer", "enemy8Attribute":"Star", "enemy9HP":0, "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":5, "name":"Semifinals: Club - Dawn of Science {<a href= \"https://fategrandorder.fandom.com/wiki/Battle_in_New_York_2018#Club\">wiki</a>}",
"enemy1HP":13052 , "enemy1Class":"Caster", "enemy1Attribute":"Man", "enemy2HP":14011 , "enemy2Class":"Caster", "enemy2Attribute":"Man", "enemy3HP":0, "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":16540 , "enemy4Class":"Caster", "enemy4Attribute":"Man", "enemy5HP":18236 , "enemy5Class":"Caster", "enemy5Attribute":"Man", "enemy6HP":30127 , "enemy6Class":"Caster", "enemy6Attribute":"Man",
"enemy7HP":70765 , "enemy7Class":"Caster", "enemy7Attribute":"Man", "enemy8HP":41412 , "enemy8Class":"Caster", "enemy8Attribute":"Man", "enemy9HP":0, "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":6, "name":"Semifinals: Gym - The Road Rollers {<a href= \"https://fategrandorder.fandom.com/wiki/Battle_in_New_York_2018#Gym\">wiki</a>}",
"enemy1HP":14951 , "enemy1Class":"Rider", "enemy1Attribute":"Earth", "enemy2HP":18046 , "enemy2Class":"Rider", "enemy2Attribute":"Earth", "enemy3HP":16092 , "enemy3Class":"Rider", "enemy3Attribute":"Earth",
"enemy4HP":16662 , "enemy4Class":"Rider", "enemy4Attribute":"Earth", "enemy5HP":52177 , "enemy5Class":"Rider", "enemy5Attribute":"Earth", "enemy6HP":23983 , "enemy6Class":"Rider", "enemy6Attribute":"Earth",
"enemy7HP":101564 , "enemy7Class":"Rider", "enemy7Attribute":"Earth", "enemy8HP":60475 , "enemy8Class":"Rider", "enemy8Attribute":"Man", "enemy9HP":0, "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":7, "name":"Semifinals: Garden - Fuuma Clan's Ambition {<a href= \"https://fategrandorder.fandom.com/wiki/Battle_in_New_York_2018#Garden\">wiki</a>}",
"enemy1HP":11372 , "enemy1Class":"Assassin", "enemy1Attribute":"Earth", "enemy2HP":12432 , "enemy2Class":"Assassin", "enemy2Attribute":"Earth", "enemy3HP":32374 , "enemy3Class":"Assassin", "enemy3Attribute":"Earth",
"enemy4HP":13116 , "enemy4Class":"Assassin", "enemy4Attribute":"Earth", "enemy5HP":34646 , "enemy5Class":"Assassin", "enemy5Attribute":"Earth", "enemy6HP":82299 , "enemy6Class":"Assassin", "enemy6Attribute":"Earth",
"enemy7HP":100857 , "enemy7Class":"Assassin", "enemy7Attribute":"Man", "enemy8HP":162592 , "enemy8Class":"Assassin", "enemy8Attribute":"Earth", "enemy9HP":0, "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":8, "name":"Finals: Club - Dream Co-Appearance {<a href= \"https://fategrandorder.fandom.com/wiki/Battle_in_New_York_2018#Club\">wiki</a>}",
"enemy1HP":10448 , "enemy1Class":"Rider", "enemy1Attribute":"Man", "enemy2HP":11164 , "enemy2Class":"Rider", "enemy2Attribute":"Man", "enemy3HP":14847 , "enemy3Class":"Rider", "enemy3Attribute":"Man",
"enemy4HP":16232 , "enemy4Class":"Rider", "enemy4Attribute":"Man", "enemy5HP":31342 , "enemy5Class":"Rider", "enemy5Attribute":"Man", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":73550 , "enemy7Class":"Rider", "enemy7Attribute":"Star", "enemy8HP":43435 , "enemy8Class":"Rider", "enemy8Attribute":"Man", "enemy9HP":0, "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":9, "name":"Finals: Gym - NY Sightseeing Tour {<a href= \"https://fategrandorder.fandom.com/wiki/Battle_in_New_York_2018#Gym\">wiki</a>}",
"enemy1HP":11244 , "enemy1Class":"Saber", "enemy1Attribute":"Man", "enemy2HP":19142 , "enemy2Class":"Saber", "enemy2Attribute":"Earth", "enemy3HP":13294 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":18167 , "enemy4Class":"Saber", "enemy4Attribute":"Man", "enemy5HP":24649 , "enemy5Class":"Saber", "enemy5Attribute":"Earth", "enemy6HP":50594 , "enemy6Class":"Berserker", "enemy6Attribute":"Earth",
"enemy7HP":102970 , "enemy7Class":"Caster", "enemy7Attribute":"Sky", "enemy8HP":61253 , "enemy8Class":"Saber", "enemy8Attribute":"Sky", "enemy9HP":0, "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":10, "name":"Finals: Arena - Like An Electric Noticeboard {<a href= \"https://fategrandorder.fandom.com/wiki/Battle_in_New_York_2018#Arena\">wiki</a>}",
"enemy1HP":13364 , "enemy1Class":"Lancer", "enemy1Attribute":"Sky", "enemy2HP":13940 , "enemy2Class":"Lancer", "enemy2Attribute":"Sky", "enemy3HP":23073 , "enemy3Class":"Lancer", "enemy3Attribute":"Sky",
"enemy4HP":71451 , "enemy4Class":"Lancer", "enemy4Attribute":"Earth", "enemy5HP":15091 , "enemy5Class":"Lancer", "enemy5Attribute":"Sky", "enemy6HP":32946 , "enemy6Class":"Lancer", "enemy6Attribute":"Sky",
"enemy7HP":153000 , "enemy7Class":"Lancer", "enemy7Attribute":"Sky", "enemy8HP":80205 , "enemy8Class":"Lancer", "enemy8Attribute":"Earth", "enemy9HP":0, "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":11, "name":"Finals: Garden - Princess and her Bodyguard {<a href= \"https://fategrandorder.fandom.com/wiki/Battle_in_New_York_2018#Garden\">wiki</a>}",
"enemy1HP":14584 , "enemy1Class":"Assassin", "enemy1Attribute":"Sky", "enemy2HP":17453 , "enemy2Class":"Assassin", "enemy2Attribute":"Sky", "enemy3HP":28468 , "enemy3Class":"Assassin", "enemy3Attribute":"Sky",
"enemy4HP":18239 , "enemy4Class":"Assassin", "enemy4Attribute":"Sky", "enemy5HP":29644 , "enemy5Class":"Assassin", "enemy5Attribute":"Sky", "enemy6HP":80392 , "enemy6Class":"Saber", "enemy6Attribute":"Earth",
"enemy7HP":163352 , "enemy7Class":"Saber", "enemy7Attribute":"Man", "enemy8HP":102360 , "enemy8Class":"Assassin", "enemy8Attribute":"Earth", "enemy9HP":0, "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":12, "name":"Proof of Hero: Pirate Ship (Okeanos) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Okeanos#Pirate_Ship\">wiki</a>}",
"enemy1HP":3136 , "enemy1Class":"Archer", "enemy1Attribute":"Man", "enemy2HP":3136 , "enemy2Class":"Archer", "enemy2Attribute":"Man", "enemy3HP":3136 , "enemy3Class":"Archer", "enemy3Attribute":"Man",
"enemy4HP":3838, "enemy4Class":"Saber", "enemy4Attribute":"Man", "enemy5HP":3838 , "enemy5Class":"Saber", "enemy5Attribute":"Man","enemy6HP":3838 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":13332, "enemy7Class":"Saber", "enemy7Attribute":"Man", "enemy8HP":8232 , "enemy8Class":"Archer", "enemy8Attribute":"Man","enemy9HP":8232 , "enemy9Class":"Archer", "enemy9Attribute":"Man"},
{"id":13, "name":"Evil Bone: Unknown Coordinates X-G (Fuyuki) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Fuyuki#Unknown_Coordinates_X-G\">wiki</a>}",
"enemy1HP":8667 , "enemy1Class":"Saber", "enemy1Attribute":"Man", "enemy2HP":9087 , "enemy2Class":"Saber", "enemy2Attribute":"Man", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":9177 , "enemy4Class":"Lancer", "enemy4Attribute":"Man", "enemy5HP":3838 , "enemy5Class":"Archer", "enemy5Attribute":"Man","enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":8753 , "enemy7Class":"Lancer", "enemy7Attribute":"Man", "enemy8HP":8753, "enemy8Class":"Lancer", "enemy8Attribute":"Man","enemy9HP":10388 , "enemy9Class":"Lancer", "enemy9Attribute":"Man"},
{"id":14, "name":"Dragon Fang: Deming (E Pluribus Unum) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_E_Pluribus_Unum#Deming\">wiki</a>}",
"enemy1HP":12869 , "enemy1Class":"Rider", "enemy1Attribute":"Earth", "enemy2HP":12869 , "enemy2Class":"Rider", "enemy2Attribute":"Earth", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":24806 , "enemy4Class":"Rider", "enemy4Attribute":"Earth", "enemy5HP":20320 , "enemy5Class":"Rider", "enemy5Attribute":"Earth", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":49859 , "enemy7Class":"Rider", "enemy7Attribute":"Earth", "enemy8HP":109641 , "enemy8Class":"Rider", "enemy8Attribute":"Earth", "enemy9HP":49859 , "enemy9Class":"Rider", "enemy9Attribute":"Earth"},
{"id":15, "name":"Void's Dust: Charlotte (E Pluribus Unum) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_E_Pluribus_Unum#Charlotte\">wiki</a>}",
"enemy1HP":17052 , "enemy1Class":"Caster", "enemy1Attribute":"Man", "enemy2HP":17052 , "enemy2Class":"Archer", "enemy2Attribute":"Man", "enemy3HP":17052 , "enemy3Class":"Archer", "enemy3Attribute":"Man",
"enemy4HP":37332 , "enemy4Class":"Lancer", "enemy4Attribute":"Man", "enemy5HP":46802 , "enemy5Class":"Berserker", "enemy5Attribute":"Man","enemy6HP":50193 , "enemy6Class":"Berserker", "enemy6Attribute":"Man",
"enemy7HP":38556 , "enemy7Class":"Lancer", "enemy7Attribute":"Man", "enemy8HP":103775 , "enemy8Class":"Berserker", "enemy8Attribute":"Man","enemy9HP":103138 , "enemy9Class":"Lancer", "enemy9Attribute":"Man"},
{"id":16, "name":"Fool's Chain: Wastelands of Death (Camelot) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Camelot#Wilderness_of_Death\">wiki</a>}",
"enemy1HP":15594 , "enemy1Class":"Assassin", "enemy1Attribute":"Man", "enemy2HP":15594 , "enemy2Class":"Assassin", "enemy2Attribute":"Man", "enemy3HP":15594 , "enemy3Class":"Assassin", "enemy3Attribute":"Man",
"enemy4HP":23464 , "enemy4Class":"Assassin", "enemy4Attribute":"Man", "enemy5HP":48600 , "enemy5Class":"Berserker", "enemy5Attribute":"Man", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":93312 , "enemy7Class":"Berserker", "enemy7Attribute":"Man", "enemy8HP":87091 , "enemy8Class":"Berserker", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":17, "name":"Deadly Poisonous Needle: Field of Reeds (Babylonia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Babylonia#Phragmites_Prairie_.2F_Field_of_Reeds\">wiki</a>}",
"enemy1HP":28764 , "enemy1Class":"Lancer", "enemy1Attribute":"Earth", "enemy2HP":28764 , "enemy2Class":"Lancer", "enemy2Attribute":"Earth", "enemy3HP":28764 , "enemy3Class":"Lancer", "enemy3Attribute":"Earth",
"enemy4HP":37864 , "enemy4Class":"Lancer", "enemy4Attribute":"Earth", "enemy5HP":37864 , "enemy5Class":"Lancer", "enemy5Attribute":"Earth", "enemy6HP":37864 , "enemy6Class":"Lancer", "enemy6Attribute":"Earth",
"enemy7HP":122015 , "enemy7Class":"Lancer", "enemy7Attribute":"Earth", "enemy8HP":86034 , "enemy8Class":"Lancer", "enemy8Attribute":"Earth", "enemy9HP":86034 , "enemy9Class":"Lancer", "enemy9Attribute":"Earth"},
{"id":18, "name":"Mystic Spinal Fluid: Shinjuku Station (Shinjuku) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Shinjuku#Shinjuku_Station\">wiki</a>}",
"enemy1HP":24225 , "enemy1Class":"Archer", "enemy1Attribute":"Man", "enemy2HP":13867 , "enemy2Class":"Archer", "enemy2Attribute":"Man", "enemy3HP":13867 , "enemy3Class":"Archer", "enemy3Attribute":"Man",
"enemy4HP":17991 , "enemy4Class":"Archer", "enemy4Attribute":"Man", "enemy5HP":17991 , "enemy5Class":"Archer", "enemy5Attribute":"Man", "enemy6HP":30937 , "enemy6Class":"Archer", "enemy6Attribute":"Man",
"enemy7HP":92977 , "enemy7Class":"Archer", "enemy7Attribute":"Man", "enemy8HP":115889 , "enemy8Class":"Archer", "enemy8Attribute":"Man", "enemy9HP":92977 , "enemy9Class":"Archer", "enemy9Attribute":"Man"},
{"id":19, "name":"Stake of Wailing Night: Gallows Hill (Salem) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Salem#Gallow_Hill\">wiki</a>}",
"enemy1HP":11866 , "enemy1Class":"Berserker", "enemy1Attribute":"Earth", "enemy2HP":13077 , "enemy2Class":"Berserker", "enemy2Attribute":"Earth", "enemy3HP":13057 , "enemy3Class":"Berserker", "enemy3Attribute":"Earth",
"enemy4HP":38912 , "enemy4Class":"Assassin", "enemy4Attribute":"Earth", "enemy5HP":15206 , "enemy5Class":"Berserker", "enemy5Attribute":"Earth", "enemy6HP":16695 , "enemy6Class":"Berserker", "enemy6Attribute":"Earth",
"enemy7HP":46866 , "enemy7Class":"Berserker", "enemy7Attribute":"Earth", "enemy8HP":192012 , "enemy8Class":"Assassin", "enemy8Attribute":"Earth", "enemy9HP":51180 , "enemy9Class":"Assassin", "enemy9Attribute":"Earth"},
{"id":20, "name":"Mystic Gunpowder: Yaga Smolensk (Anastasia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Anastasia#Yaga_Smolensk\">wiki</a>}",
"enemy1HP":16923 , "enemy1Class":"Saber", "enemy1Attribute":"Earth", "enemy2HP":16732 , "enemy2Class":"Assassin", "enemy2Attribute":"Earth", "enemy3HP":14847 , "enemy3Class":"Saber", "enemy3Attribute":"Earth",
"enemy4HP":25886 , "enemy4Class":"Saber", "enemy4Attribute":"Earth", "enemy5HP":26456 , "enemy5Class":"Saber", "enemy5Attribute":"Earth", "enemy6HP":16732 , "enemy6Class":"Assassin", "enemy6Attribute":"Earth",
"enemy7HP":160815 , "enemy7Class":"Saber", "enemy7Attribute":"Earth", "enemy8HP":45301 , "enemy8Class":"Assassin", "enemy8Attribute":"Earth", "enemy9HP":46995 , "enemy9Class":"Assassin", "enemy9Attribute":"Earth"},
{"id":21, "name":"Seed of Yggdrasil: Fallen Babylon (Babylonia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Babylonia#Abolished_Metropolis_Babylon\">wiki</a>}",
"enemy1HP":16552 , "enemy1Class":"Rider", "enemy1Attribute":"Earth", "enemy2HP":16552 , "enemy2Class":"Rider", "enemy2Attribute":"Earth", "enemy3HP":16552 , "enemy3Class":"Rider", "enemy3Attribute":"Earth",
"enemy4HP":30300 , "enemy4Class":"Rider", "enemy4Attribute":"Earth", "enemy5HP":30300 , "enemy5Class":"Rider", "enemy5Attribute":"Earth", "enemy6HP":30300 , "enemy6Class":"Rider", "enemy6Attribute":"Earth",
"enemy7HP":92385 , "enemy7Class":"Rider", "enemy7Attribute":"Earth", "enemy8HP":79221 , "enemy8Class":"Rider", "enemy8Attribute":"Earth", "enemy9HP":79221 , "enemy9Class":"Rider", "enemy9Attribute":"Earth"},
{"id":22, "name":"Ghost Lantern: Kutha (Babylonia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Babylonia#Cuthah\">wiki</a>}",
"enemy1HP":20468 , "enemy1Class":"Assassin", "enemy1Attribute":"Sky", "enemy2HP":20468 , "enemy2Class":"Assassin", "enemy2Attribute":"Sky", "enemy3HP":27255 , "enemy3Class":"Assassin", "enemy3Attribute":"Sky",
"enemy4HP":43319 , "enemy4Class":"Assassin", "enemy4Attribute":"Sky", "enemy5HP":43319 , "enemy5Class":"Assassin", "enemy5Attribute":"Sky", "enemy6HP":66333 , "enemy6Class":"Assassin", "enemy6Attribute":"Sky",
"enemy7HP":273999 , "enemy7Class":"Assassin", "enemy7Attribute":"Sky", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":23, "name":"Octuplet Crystal: Peach Blossom Shangri-La (Agartha) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Agartha#Peach_Blossom_Spring\">wiki</a>}",
"enemy1HP":16656 , "enemy1Class":"Berserker", "enemy1Attribute":"Sky", "enemy2HP":17540 , "enemy2Class":"Berserker", "enemy2Attribute":"Sky", "enemy3HP":16656 , "enemy3Class":"Berserker", "enemy3Attribute":"Sky",
"enemy4HP":26500 , "enemy4Class":"Berserker", "enemy4Attribute":"Sky", "enemy5HP":25616 , "enemy5Class":"Berserker", "enemy5Attribute":"Sky", "enemy6HP":24172 , "enemy6Class":"Berserker", "enemy6Attribute":"Sky",
"enemy7HP":277318 , "enemy7Class":"Berserker", "enemy7Attribute":"Sky", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":24, "name":"Serpent Jewel: Chasm in the Earth (Agartha) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Agartha#Chasm_on_The_Ground\">wiki</a>}",
"enemy1HP":13202 , "enemy1Class":"Caster", "enemy1Attribute":"Earth", "enemy2HP":12649 , "enemy2Class":"Caster", "enemy2Attribute":"Earth", "enemy3HP":12649 , "enemy3Class":"Caster", "enemy3Attribute":"Earth",
"enemy4HP":19644 , "enemy4Class":"Caster", "enemy4Attribute":"Earth", "enemy5HP":19644 , "enemy5Class":"Caster", "enemy5Attribute":"Earth", "enemy6HP":25665 , "enemy6Class":"Caster", "enemy6Attribute":"Earth",
"enemy7HP":68311 , "enemy7Class":"Caster", "enemy7Attribute":"Earth", "enemy8HP":232310 , "enemy8Class":"Caster", "enemy8Attribute":"Earth", "enemy9HP":68311 , "enemy9Class":"Caster", "enemy9Attribute":"Earth"},
{"id":25, "name":"Phoenix Feather: Town Hall (Salem) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Salem#Town_Hall\">wiki</a>}",
"enemy1HP":22291 , "enemy1Class":"Caster", "enemy1Attribute":"Earth", "enemy2HP":21738 , "enemy2Class":"Caster", "enemy2Attribute":"Earth", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":40932 , "enemy4Class":"Caster", "enemy4Attribute":"Earth", "enemy5HP":29722 , "enemy5Class":"Caster", "enemy5Attribute":"Earth", "enemy6HP":29722 , "enemy6Class":"Caster", "enemy6Attribute":"Earth",
"enemy7HP":85551 , "enemy7Class":"Caster", "enemy7Attribute":"Earth", "enemy8HP":176556 , "enemy8Class":"Caster", "enemy8Attribute":"Earth", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":26, "name":"Eternal Gear: Barrel Tower (Shinjuku) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Shinjuku#Barrel_Tower\">wiki</a>}",
"enemy1HP":11457 , "enemy1Class":"Assassin", "enemy1Attribute":"Sky", "enemy2HP":18393 , "enemy2Class":"Assassin", "enemy2Attribute":"Sky", "enemy3HP":11457 , "enemy3Class":"Assassin", "enemy3Attribute":"Sky",
"enemy4HP":27204 , "enemy4Class":"Assassin", "enemy4Attribute":"Sky", "enemy5HP":32474 , "enemy5Class":"Assassin", "enemy5Attribute":"Sky", "enemy6HP":27204 , "enemy6Class":"Assassin", "enemy6Attribute":"Sky",
"enemy7HP":74846 , "enemy7Class":"Assassin", "enemy7Attribute":"Sky", "enemy8HP":74846 , "enemy8Class":"Assassin", "enemy8Attribute":"Sky", "enemy9HP":174084 , "enemy9Class":"Assassin", "enemy9Attribute":"Sky"},
{"id":27, "name":"Forbidden Page: Shinjuku 2-chome (Shinjuku) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Shinjuku#Shinjuku_2-chome\">wiki</a>}",
"enemy1HP":16462 , "enemy1Class":"Caster", "enemy1Attribute":"Sky", "enemy2HP":19972 , "enemy2Class":"Caster", "enemy2Attribute":"Sky", "enemy3HP":19972 , "enemy3Class":"Caster", "enemy3Attribute":"Sky",
"enemy4HP":25847 , "enemy4Class":"Caster", "enemy4Attribute":"Sky", "enemy5HP":25847 , "enemy5Class":"Caster", "enemy5Attribute":"Sky", "enemy6HP":36680 , "enemy6Class":"Caster", "enemy6Attribute":"Sky",
"enemy7HP":262183 , "enemy7Class":"Lancer", "enemy7Attribute":"Earth", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":28, "name":"Homunculus Baby: Whateley Residence (Salem) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Salem#Whateley_House\">wiki</a>}",
"enemy1HP":10986 , "enemy1Class":"Lancer", "enemy1Attribute":"Sky", "enemy2HP":10986 , "enemy2Class":"Lancer", "enemy2Attribute":"Sky", "enemy3HP":11505 , "enemy3Class":"Lancer", "enemy3Attribute":"Sky",
"enemy4HP":20913 , "enemy4Class":"Lancer", "enemy4Attribute":"Sky", "enemy5HP":20913 , "enemy5Class":"Lancer", "enemy5Attribute":"Sky", "enemy6HP":24749 , "enemy6Class":"Lancer", "enemy6Attribute":"Sky",
"enemy7HP":64306 , "enemy7Class":"Lancer", "enemy7Attribute":"Sky", "enemy8HP":189802 , "enemy8Class":"Lancer", "enemy8Attribute":"Sky", "enemy9HP":64306 , "enemy9Class":"Lancer", "enemy9Attribute":"Sky"},
{"id":29, "name":"Meteor Horseshoe: Land of the Void (Camelot) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Camelot#Vast_Land_of_Nothingness\">wiki</a>}",
"enemy1HP":11289 , "enemy1Class":"Rider", "enemy1Attribute":"Earth", "enemy2HP":11289 , "enemy2Class":"Rider", "enemy2Attribute":"Earth", "enemy3HP":11524 , "enemy3Class":"Archer", "enemy3Attribute":"Earth",
"enemy4HP":52224 , "enemy4Class":"Rider", "enemy4Attribute":"Earth", "enemy5HP":51680 , "enemy5Class":"Assassin", "enemy5Attribute":"Earth", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":72864 , "enemy7Class":"Rider", "enemy7Attribute":"Earth", "enemy8HP":72864 , "enemy8Class":"Rider", "enemy8Attribute":"Earth", "enemy9HP":124656 , "enemy9Class":"Lancer", "enemy9Attribute":"Earth"},
{"id":30, "name":"Great Knight Medal: Royal Castle (Camelot) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Camelot#Sovereign_Castle\">wiki</a>}",
"enemy1HP":72538 , "enemy1Class":"Saber", "enemy1Attribute":"Man", "enemy2HP":72538 , "enemy2Class":"Saber", "enemy2Attribute":"Man", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":76356 , "enemy4Class":"Saber", "enemy4Attribute":"Man", "enemy5HP":76356 , "enemy5Class":"Saber", "enemy5Attribute":"Man", "enemy6HP":76356 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":204096 , "enemy7Class":"Saber", "enemy7Attribute":"Earth", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":31, "name":"Shell of Reminiscence: Observatory (Babylonia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Babylonia#Observatory\">wiki</a>}",
"enemy1HP":17847 , "enemy1Class":"Saber", "enemy1Attribute":"Earth", "enemy2HP":17847 , "enemy2Class":"Saber", "enemy2Attribute":"Earth", "enemy3HP":23219 , "enemy3Class":"Saber", "enemy3Attribute":"Earth",
"enemy4HP":21379 , "enemy4Class":"Saber", "enemy4Attribute":"Earth", "enemy5HP":36220 , "enemy5Class":"Saber", "enemy5Attribute":"Earth", "enemy6HP":36220 , "enemy6Class":"Saber", "enemy6Attribute":"Earth",
"enemy7HP":118033 , "enemy7Class":"Saber", "enemy7Attribute":"Earth", "enemy8HP":187708 , "enemy8Class":"Saber", "enemy8Attribute":"Earth", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":32, "name":"Refined Magatama: Castle Town (Shimosa) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Shimosa#Castle_Town\">wiki</a>}",
"enemy1HP":26978 , "enemy1Class":"Saber", "enemy1Attribute":"Sky", "enemy2HP":24467 , "enemy2Class":"Sky", "enemy2Attribute":"Saber", "enemy3HP":24467 , "enemy3Class":"Saber", "enemy3Attribute":"Sky",
"enemy4HP":37051 , "enemy4Class":"Saber", "enemy4Attribute":"Sky", "enemy5HP":39210 , "enemy5Class":"Sky", "enemy5Attribute":"Saber", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":54413 , "enemy7Class":"Saber", "enemy7Attribute":"Sky", "enemy8HP":54413 , "enemy8Class":"Sky", "enemy8Attribute":"Saber", "enemy9HP":196041 , "enemy9Class":"Saber", "enemy9Attribute":"Sky"},
{"id":33, "name":"Eternal Ice: Yaga Moscow (Anastasia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Anastasia#Yaga_Moscow\">wiki</a>}",
"enemy1HP":28871 , "enemy1Class":"Assassin", "enemy1Attribute":"Man", "enemy2HP":25897 , "enemy2Class":"Assassin", "enemy2Attribute":"Man", "enemy3HP":25227 , "enemy3Class":"Assassin", "enemy3Attribute":"Man",
"enemy4HP":32245 , "enemy4Class":"Assassin", "enemy4Attribute":"Man", "enemy5HP":30233 , "enemy5Class":"Assassin", "enemy5Attribute":"Man", "enemy6HP":31331 , "enemy6Class":"Assassin", "enemy6Attribute":"Man",
"enemy7HP":51500 , "enemy7Class":"Assassin", "enemy7Attribute":"Man", "enemy8HP":50274 , "enemy8Class":"Assassin", "enemy8Attribute":"Man", "enemy9HP":168434 , "enemy9Class":"Assassin", "enemy9Attribute":"Man"},
{"id":34, "name":"Giant's Ring: Giant's Flower Patio (Gotterdammerung) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_G%C3%B6tterd%C3%A4mmerung#Giants.27_Flower_Patio\">wiki</a>}",
"enemy1HP":21819 , "enemy1Class":"Berserker", "enemy1Attribute":"Earth", "enemy2HP":24771 , "enemy2Class":"Berserker", "enemy2Attribute":"Earth", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":31821 , "enemy4Class":"Berserker", "enemy4Attribute":"Earth", "enemy5HP":33774 , "enemy5Class":"Berserker", "enemy5Attribute":"Earth", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":51431 , "enemy7Class":"Berserker", "enemy7Attribute":"Earth", "enemy8HP":152001 , "enemy8Class":"Berserker", "enemy8Attribute":"Earth", "enemy9HP":53401 , "enemy9Class":"Berserker", "enemy9Attribute":"Earth"},
{"id":35, "name":"Aurora Steel: Castle of Ice and Snow (Gotterdammerung) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_G%C3%B6tterd%C3%A4mmerung#Castle_of_Ice_and_Snow\">wiki</a>}",
"enemy1HP":9884 , "enemy1Class":"Rider", "enemy1Attribute":"Sky", "enemy2HP":10889 , "enemy2Class":"Rider", "enemy2Attribute":"Sky", "enemy3HP":10644 , "enemy3Class":"Rider", "enemy3Attribute":"Sky",
"enemy4HP":30279 , "enemy4Class":"Rider", "enemy4Attribute":"Sky", "enemy5HP":24599 , "enemy5Class":"Rider", "enemy5Attribute":"Sky", "enemy6HP":33264 , "enemy6Class":"Rider", "enemy6Attribute":"Sky",
"enemy7HP":41136 , "enemy7Class":"Rider", "enemy7Attribute":"Sky", "enemy8HP":49586 , "enemy8Class":"Rider", "enemy8Attribute":"Sky", "enemy9HP":180432 , "enemy9Class":"Rider", "enemy9Attribute":"Sky"},
{"id":36, "name":"Ancient Bell of Tranquility: Eight Gates Cave (Qin) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_S_I_N#Eight_Gates_Cave\">wiki</a>}",
"enemy1HP":20232 , "enemy1Class":"Assassin", "enemy1Attribute":"Man", "enemy2HP":17588 , "enemy2Class":"Assassin", "enemy2Attribute":"Man", "enemy3HP":17588 , "enemy3Class":"Assassin", "enemy3Attribute":"Man",
"enemy4HP":24524 , "enemy4Class":"Assassin", "enemy4Attribute":"Man", "enemy5HP":26132 , "enemy5Class":"Assassin", "enemy5Attribute":"Man", "enemy6HP":25060 , "enemy6Class":"Assassin", "enemy6Attribute":"Man",
"enemy7HP":47607 , "enemy7Class":"Assassin", "enemy7Attribute":"Man", "enemy8HP":44207 , "enemy8Class":"Assassin", "enemy8Attribute":"Man", "enemy9HP":183480 , "enemy9Class":"Assassin", "enemy9Attribute":"Man"},
{"id":37, "name":"Arrowhead of Disasterous Sin: Remains of the Divine Floating Rock (Yuga Kshetra) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Yuga_Kshetra#Remains_of_the_Divine_Floating_Rock\">wiki</a>}",
"enemy1HP":24889 , "enemy1Class":"Berserker", "enemy1Attribute":"Earth", "enemy2HP":24240 , "enemy2Class":"Berserker", "enemy2Attribute":"Earth", "enemy3HP":23591 , "enemy3Class":"Berserker", "enemy3Attribute":"Earth",
"enemy4HP":34617 , "enemy4Class":"Berserker", "enemy4Attribute":"Earth", "enemy5HP":33872 , "enemy5Class":"Berserker", "enemy5Attribute":"Earth", "enemy6HP":35363 , "enemy6Class":"Berserker", "enemy6Attribute":"Earth",
"enemy7HP":58118 , "enemy7Class":"Berserker", "enemy7Attribute":"Earth", "enemy8HP":107374 , "enemy8Class":"Berserker", "enemy8Attribute":"Earth", "enemy9HP":56902 , "enemy9Class":"Berserker", "enemy9Attribute":"Earth"},
{"id":38, "name":"Moonlit Tiara: Thanatos Island (Atlantis) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Atlantis#Thanatos_Island\">wiki</a>}",
"enemy1HP":30903 , "enemy1Class":"Berserker", "enemy1Attribute":"Man", "enemy2HP":32078 , "enemy2Class":"Saber", "enemy2Attribute":"Man", "enemy3HP":30104 , "enemy3Class":"Assassin", "enemy3Attribute":"Man",
"enemy4HP":43286 , "enemy4Class":"Assassin", "enemy4Attribute":"Man", "enemy5HP":42648 , "enemy5Class":"Berserker", "enemy5Attribute":"Man", "enemy6HP":54964 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":60862 , "enemy7Class":"Saber", "enemy7Attribute":"Man", "enemy8HP":51840 , "enemy8Class":"Assassin", "enemy8Attribute":"Man", "enemy9HP":51440 , "enemy9Class":"Berserker", "enemy9Attribute":"Man"},
{"id":39, "name":"Divine Spirit Particle: Underground Organization Region - Outer Circumference (Olympus) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Olympus#Underground_Organization_Region:_Outer_Circumference\">wiki</a>}",
"enemy1HP":42989 , "enemy1Class":"Assassin", "enemy1Attribute":"Sky", "enemy2HP":37263 , "enemy2Class":"Assassin", "enemy2Attribute":"Sky", "enemy3HP":30704 , "enemy3Class":"Assassin", "enemy3Attribute":"Sky",
"enemy4HP":53385 , "enemy4Class":"Assassin", "enemy4Attribute":"Sky", "enemy5HP":44202 , "enemy5Class":"Assassin", "enemy5Attribute":"Sky", "enemy6HP":37190 , "enemy6Class":"Assassin", "enemy6Attribute":"Sky",
"enemy7HP":42996 , "enemy7Class":"Assassin", "enemy7Attribute":"Sky", "enemy8HP":51794 , "enemy8Class":"Assassin", "enemy8Attribute":"Sky", "enemy9HP":61543 , "enemy9Class":"Assassin", "enemy9Attribute":"Sky"},
{"id":40, "name":"Claw of Chaos: Des Moines (E Pluribus Unum) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_E_Pluribus_Unum#Des_Moines\">wiki</a>}",
"enemy1HP":20588 , "enemy1Class":"Assassin", "enemy1Attribute":"Earth", "enemy2HP":20588 , "enemy2Class":"Assassin", "enemy2Attribute":"Earth", "enemy3HP":20588 , "enemy3Class":"Assassin", "enemy3Attribute":"Earth",
"enemy4HP":127575 , "enemy4Class":"Berserker", "enemy4Attribute":"Earth", "enemy5HP":0 , "enemy5Class":"Saber", "enemy5Attribute":"Man", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":148656 , "enemy7Class":"Lancer", "enemy7Attribute":"Man", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":41, "name":"Heart of the Foreign God: Carter Residence (Salem) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Salem#Carter_House\">wiki</a>}",
"enemy1HP":30685 , "enemy1Class":"Assassin", "enemy1Attribute":"Earth", "enemy2HP":35865 , "enemy2Class":"Assassin", "enemy2Attribute":"Earth", "enemy3HP":30685 , "enemy3Class":"Assassin", "enemy3Attribute":"Earth",
"enemy4HP":40944 , "enemy4Class":"Assassin", "enemy4Attribute":"Earth", "enemy5HP":38912 , "enemy5Class":"Assassin", "enemy5Attribute":"Earth", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":199841 , "enemy7Class":"Caster", "enemy7Attribute":"Sky", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":42, "name":"Dragon's Reverse Scale: Nippur (Babylonia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Babylonia#Nippur\">wiki</a>}",
"enemy1HP":25169 , "enemy1Class":"Lancer", "enemy1Attribute":"Earth", "enemy2HP":25169 , "enemy2Class":"Lancer", "enemy2Attribute":"Earth", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":39137 , "enemy4Class":"Lancer", "enemy4Attribute":"Earth", "enemy5HP":39137 , "enemy5Class":"Lancer", "enemy5Attribute":"Earth", "enemy6HP":39137 , "enemy6Class":"Lancer", "enemy6Attribute":"Earth",
"enemy7HP":288970 , "enemy7Class":"Rider", "enemy7Attribute":"Earth", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":43, "name":"Spirit Root: Holy City (Camelot) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Camelot#Holy_City_Districts\">wiki</a>}",
"enemy1HP":23760 , "enemy1Class":"Berserker", "enemy1Attribute":"Sky", "enemy2HP":11781 , "enemy2Class":"Lancer", "enemy2Attribute":"Man", "enemy3HP":11781 , "enemy3Class":"Lancer", "enemy3Attribute":"Man",
"enemy4HP":26730 , "enemy4Class":"Berserker", "enemy4Attribute":"Sky", "enemy5HP":26730 , "enemy5Class":"Berserker", "enemy5Attribute":"Sky", "enemy6HP":13901 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":236087 , "enemy7Class":"Saber", "enemy7Attribute":"Earth", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":44, "name":"Warhorse's Young Horn: Initiate Point (Yuga Ksehtra) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Yuga_Kshetra#Initiate_Point\">wiki</a>}",
"enemy1HP":25844 , "enemy1Class":"Berserker", "enemy1Attribute":"Earth", "enemy2HP":25844 , "enemy2Class":"Berserker", "enemy2Attribute":"Earth", "enemy3HP":20368 , "enemy3Class":"Berserker", "enemy3Attribute":"Earth",
"enemy4HP":30989 , "enemy4Class":"Berserker", "enemy4Attribute":"Earth", "enemy5HP":52165 , "enemy5Class":"Lancer", "enemy5Attribute":"Sky", "enemy6HP":30291 , "enemy6Class":"Berserker", "enemy6Attribute":"Earth",
"enemy7HP":77177 , "enemy7Class":"Lancer", "enemy7Attribute":"Sky", "enemy8HP":104549 , "enemy8Class":"Lancer", "enemy8Attribute":"Sky", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":45, "name":"(NA) Warhorse's Young Horn: Campsite (Agartha) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Agartha#Campsite\">wiki</a>}",
"enemy1HP":11550 , "enemy1Class":"Lancer", "enemy1Attribute":"Man", "enemy2HP":11359 , "enemy2Class":"Lancer", "enemy2Attribute":"Man", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":25803 , "enemy4Class":"Lancer", "enemy4Attribute":"Man", "enemy5HP":13697 , "enemy5Class":"Lancer", "enemy5Attribute":"Man", "enemy6HP":13697 , "enemy6Class":"Lancer", "enemy6Attribute":"Man",
"enemy7HP":58828 , "enemy7Class":"Lancer", "enemy7Attribute":"Man", "enemy8HP":32378 , "enemy8Class":"Lancer", "enemy8Attribute":"Man", "enemy9HP":254518 , "enemy9Class":"Lancer", "enemy9Attribute":"Earth"},
{"id":46, "name":"Tearstone of Blood: Shinjuku 2-Chome (Shinjuku) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Shinjuku#Shinjuku_2-chome\">wiki</a>}",
"enemy1HP":16462 , "enemy1Class":"Caster", "enemy1Attribute":"Sky", "enemy2HP":19972 , "enemy2Class":"Caster", "enemy2Attribute":"Sky", "enemy3HP":19972 , "enemy3Class":"Caster", "enemy3Attribute":"Sky",
"enemy4HP":25847 , "enemy4Class":"Caster", "enemy4Attribute":"Sky", "enemy5HP":25847 , "enemy5Class":"Caster", "enemy5Attribute":"Sky", "enemy6HP":36680 , "enemy6Class":"Caster", "enemy6Attribute":"Sky",
"enemy7HP":262183 , "enemy7Class":"Archer", "enemy7Attribute":"Earth", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":47, "name":"Black Beast Grease: Northern Cliffs (Agartha) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Agartha#Northern_Palisade\">wiki</a>}",
"enemy1HP":23988 , "enemy1Class":"Assassin", "enemy1Attribute":"Man", "enemy2HP":23988 , "enemy2Class":"Assassin", "enemy2Attribute":"Man", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":38953 , "enemy4Class":"Assassin", "enemy4Attribute":"Man", "enemy5HP":43410 , "enemy5Class":"Assassin", "enemy5Attribute":"Man", "enemy6HP":38953 , "enemy6Class":"Assassin", "enemy6Attribute":"Man",
"enemy7HP":266255 , "enemy7Class":"Assassin", "enemy7Attribute":"Earth", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":48, "name":"(JP) Black Beast Grease: Secluded Grotto (Yuga Ksehtra) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Yuga_Kshetra#Secluded_Grotto\">wiki</a>}",
"enemy1HP":19880 , "enemy1Class":"Berserker", "enemy1Attribute":"Earth", "enemy2HP":20410 , "enemy2Class":"Berserker", "enemy2Attribute":"Earth", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":33501 , "enemy4Class":"Berserker", "enemy4Attribute":"Earth", "enemy5HP":47073 , "enemy5Class":"Assassin", "enemy5Attribute":"Sky", "enemy6HP":33501 , "enemy6Class":"Berserker", "enemy6Attribute":"Earth",
"enemy7HP":106893 , "enemy7Class":"Assassin", "enemy7Attribute":"Sky", "enemy8HP":45062 , "enemy8Class":"Berserker", "enemy8Attribute":"Earth", "enemy9HP":70991 , "enemy9Class":"Assassin", "enemy9Attribute":"Sky"},
{"id":49, "name":"Lamp of Evil Sealing: Jail (Salem) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Salem#Jail\">wiki</a>}",
"enemy1HP":10879 , "enemy1Class":"Saber", "enemy1Attribute":"Earth", "enemy2HP":11135 , "enemy2Class":"Saber", "enemy2Attribute":"Earth", "enemy3HP":10879 , "enemy3Class":"Saber", "enemy3Attribute":"Earth",
"enemy4HP":15531 , "enemy4Class":"Saber", "enemy4Attribute":"Earth", "enemy5HP":15531 , "enemy5Class":"Saber", "enemy5Attribute":"Earth", "enemy6HP":15873 , "enemy6Class":"Saber", "enemy6Attribute":"Earth",
"enemy7HP":49820 , "enemy7Class":"Saber", "enemy7Attribute":"Earth", "enemy8HP":196767 , "enemy8Class":"Caster", "enemy8Attribute":"Earth", "enemy9HP":49820 , "enemy9Class":"Saber", "enemy9Attribute":"Earth"},
{"id":50, "name":"Scarab of Wisdom: Great Temple (Camelot) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Camelot#Great_Temple\">wiki</a>}",
"enemy1HP":14337 , "enemy1Class":"Berserker", "enemy1Attribute":"Man", "enemy2HP":11010 , "enemy2Class":"Assassin", "enemy2Attribute":"Man", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":20071 , "enemy4Class":"Berserker", "enemy4Attribute":"Man", "enemy5HP":20071 , "enemy5Class":"Berserker", "enemy5Attribute":"Man", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":197521 , "enemy7Class":"Caster", "enemy7Attribute":"Earth", "enemy8HP":183173 , "enemy8Class":"Caster", "enemy8Attribute":"Earth", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":51, "name":"(JP) Scarab of Wisdom: Deimos Island (Atlantis) {WARNING! This quest has special effects, please check <a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Atlantis#Deimos_Island\">wiki</a>}",
"enemy1HP":27755 , "enemy1Class":"Saber", "enemy1Attribute":"Man", "enemy2HP":27755 , "enemy2Class":"Saber", "enemy2Attribute":"Man", "enemy3HP":29620 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":31009 , "enemy4Class":"Saber", "enemy4Attribute":"Man", "enemy5HP":67256 , "enemy5Class":"Caster", "enemy5Attribute":"Earth", "enemy6HP":31009 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":88435 , "enemy7Class":"Caster", "enemy7Attribute":"Earth", "enemy8HP":34077 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":34077 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":52, "name":"Primodial Lanugo: Blood Fort (Babylonia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Babylonia#Blood_Fort_Andromeda\">wiki</a>}",
"enemy1HP":19243 , "enemy1Class":"Rider", "enemy1Attribute":"Earth", "enemy2HP":19243 , "enemy2Class":"Rider", "enemy2Attribute":"Earth", "enemy3HP":19243 , "enemy3Class":"Rider", "enemy3Attribute":"Earth",
"enemy4HP":182476 , "enemy4Class":"Rider", "enemy4Attribute":"Earth", "enemy5HP":254016 , "enemy5Class":"Rider", "enemy5Attribute":"Earth", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":0 , "enemy7Class":"Saber", "enemy7Attribute":"Man", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":53, "name":"Cursed Beast Gallstone: Arakawa Prairie (Shimosa) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Shimosa#Arakawa_Prairie\">wiki</a>}",
"enemy1HP":23831 , "enemy1Class":"Saber", "enemy1Attribute":"Sky", "enemy2HP":23831 , "enemy2Class":"Saber", "enemy2Attribute":"Sky", "enemy3HP":24506 , "enemy3Class":"Saber", "enemy3Attribute":"Sky",
"enemy4HP":108207 , "enemy4Class":"Berserker", "enemy4Attribute":"Earth", "enemy5HP":0 , "enemy5Class":"Saber", "enemy5Attribute":"Man", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":38130 , "enemy7Class":"Saber", "enemy7Attribute":"Sky", "enemy8HP":152815 , "enemy8Class":"Sky", "enemy8Attribute":"Rider", "enemy9HP":38130 , "enemy9Class":"Saber", "enemy9Attribute":"Sky"},
{"id":54, "name":"Mysterious Divine Wine: Palace of Dragon King (Agartha) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Agartha#Palace_of_the_Dragon_King\">wiki</a>}",
"enemy1HP":10055 , "enemy1Class":"Rider", "enemy1Attribute":"Man", "enemy2HP":10055 , "enemy2Class":"Rider", "enemy2Attribute":"Man", "enemy3HP":10451 , "enemy3Class":"Rider", "enemy3Attribute":"Man",
"enemy4HP":11955 , "enemy4Class":"Rider", "enemy4Attribute":"Man", "enemy5HP":11015 , "enemy5Class":"Rider", "enemy5Attribute":"Man", "enemy6HP":11015 , "enemy6Class":"Rider", "enemy6Attribute":"Man",
"enemy7HP":344794 , "enemy7Class":"Archer", "enemy7Attribute":"Earth", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":55, "name":"Dawnlight Reactor Core: Detention Centre (Qin) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_S_I_N#Detention_Centre\">wiki</a>}",
"enemy1HP":16342 , "enemy1Class":"Assassin", "enemy1Attribute":"Man", "enemy2HP":15136 , "enemy2Class":"Assassin", "enemy2Attribute":"Man", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":20141 , "enemy4Class":"Assassin", "enemy4Attribute":"Man", "enemy5HP":20141 , "enemy5Class":"Assassin", "enemy5Attribute":"Man", "enemy6HP":50502 , "enemy6Class":"Archer", "enemy6Attribute":"Sky",
"enemy7HP":80684 , "enemy7Class":"Archer", "enemy7Attribute":"Sky", "enemy8HP":178837 , "enemy8Class":"Archer", "enemy8Attribute":"Sky", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":56, "name":"Tsukumo Mirror: Trembling in Fear (Shimosa) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Shimosa#Hill_Behind_The_Hermitage\">wiki</a>}",
"enemy1HP":30627 , "enemy1Class":"Assassin", "enemy1Attribute":"Sky", "enemy2HP":31565 , "enemy2Class":"Assassin", "enemy2Attribute":"Sky", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":42490 , "enemy4Class":"Assassin", "enemy4Attribute":"Sky", "enemy5HP":34379 , "enemy5Class":"Assassin", "enemy5Attribute":"Sky", "enemy6HP":32503 , "enemy6Class":"Assassin", "enemy6Attribute":"Sky",
"enemy7HP":160487 , "enemy7Class":"Assassin", "enemy7Attribute":"Earth", "enemy8HP":70506 , "enemy8Class":"Assassin", "enemy8Attribute":"Sky", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":57, "name":"Egg of Truth: Deewar (Yuga Ksehtra) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Yuga_Kshetra#Dewar\">wiki</a>}",
"enemy1HP":29820 , "enemy1Class":"Berserker", "enemy1Attribute":"Earth", "enemy2HP":29820 , "enemy2Class":"Berserker", "enemy2Attribute":"Earth", "enemy3HP":32058 , "enemy3Class":"Berserker", "enemy3Attribute":"Earth",
"enemy4HP":40201 , "enemy4Class":"Berserker", "enemy4Attribute":"Earth", "enemy5HP":39335 , "enemy5Class":"Berserker", "enemy5Attribute":"Earth", "enemy6HP":41067 , "enemy6Class":"Berserker", "enemy6Attribute":"Earth",
"enemy7HP":175857 , "enemy7Class":"Lancer", "enemy7Attribute":"Sky", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":58, "name":"Glittering Star Shard: Machine God's Cloister (Olympus) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Olympus#Machine_God.27s_Cloister\">wiki</a>}",
"enemy1HP":30420 , "enemy1Class":"Caster", "enemy1Attribute":"Earth", "enemy2HP":31499 , "enemy2Class":"Caster", "enemy2Attribute":"Earth", "enemy3HP":30420 , "enemy3Class":"Caster", "enemy3Attribute":"Earth",
"enemy4HP":40391 , "enemy4Class":"Caster", "enemy4Attribute":"Earth", "enemy5HP":40391 , "enemy5Class":"Caster", "enemy5Attribute":"Earth", "enemy6HP":42421 , "enemy6Class":"Caster", "enemy6Attribute":"Earth",
"enemy7HP":51816 , "enemy7Class":"Caster", "enemy7Attribute":"Earth", "enemy8HP":126833 , "enemy8Class":"Rider", "enemy8Attribute":"Earth", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":59, "name":"Fruit of Eternity: Interstellar City East (Olympus) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Olympus#Interstellar_City:_East\">wiki</a>}",
"enemy1HP":25243 , "enemy1Class":"Berserker", "enemy1Attribute":"Sky", "enemy2HP":35830 , "enemy2Class":"Berserker", "enemy2Attribute":"Sky", "enemy3HP":25754 , "enemy3Class":"Berserker", "enemy3Attribute":"Sky",
"enemy4HP":59955 , "enemy4Class":"Lancer", "enemy4Attribute":"Man", "enemy5HP":30306 , "enemy5Class":"Berserker", "enemy5Attribute":"Sky", "enemy6HP":30954 , "enemy6Class":"Berserker", "enemy6Attribute":"Sky",
"enemy7HP":40481 , "enemy7Class":"Berserker", "enemy7Attribute":"Sky", "enemy8HP":50164 , "enemy8Class":"Berserker", "enemy8Attribute":"Sky", "enemy9HP":74983 , "enemy9Class":"Lancer", "enemy9Attribute":"Man"},
{"id":60, "name":"Fruit of Eternity: Interstellar City West (Olympus) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Olympus#Interstellar_City:_West\">wiki</a>}",
"enemy1HP":51959 , "enemy1Class":"Lancer", "enemy1Attribute":"Sky", "enemy2HP":0 , "enemy2Class":"Saber", "enemy2Attribute":"Man", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":100357 , "enemy4Class":"Lancer", "enemy4Attribute":"Man", "enemy5HP":0 , "enemy5Class":"Saber", "enemy5Attribute":"Man", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":148570 , "enemy7Class":"Lancer", "enemy7Attribute":"Man", "enemy8HP":71735 , "enemy8Class":"Lancer", "enemy8Attribute":"Sky", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":61, "name":"Fruit of Eternity: Interstellar City South (Olympus) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Olympus#Interstellar_City:_South\">wiki</a>}",
"enemy1HP":26296 , "enemy1Class":"Assassin", "enemy1Attribute":"Sky", "enemy2HP":27126 , "enemy2Class":"Assassin", "enemy2Attribute":"Sky", "enemy3HP":27126 , "enemy3Class":"Assassin", "enemy3Attribute":"Sky",
"enemy4HP":30212 , "enemy4Class":"Assassin", "enemy4Attribute":"Sky", "enemy5HP":70250 , "enemy5Class":"Lancer", "enemy5Attribute":"Man", "enemy6HP":31110 , "enemy6Class":"Assassin", "enemy6Attribute":"Sky",
"enemy7HP":90917 , "enemy7Class":"Lancer", "enemy7Attribute":"Man", "enemy8HP":35362 , "enemy8Class":"Assassin", "enemy8Attribute":"Sky", "enemy9HP":34397 , "enemy9Class":"Assassin", "enemy9Attribute":"Sky"}
]
