// common farming nodes
const Nodes = [
{"id":12, "name":"Proof of Hero: Pirate Ship (Okeanos) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Okeanos#Pirate_Ship\" target=\"_blank\">wiki</a>}",
"enemy1HP":3136 , "enemy1Class":"Archer", "enemy1Attribute":"Man", "enemy2HP":3136 , "enemy2Class":"Archer", "enemy2Attribute":"Man", "enemy3HP":3136 , "enemy3Class":"Archer", "enemy3Attribute":"Man",
"enemy4HP":3838, "enemy4Class":"Saber", "enemy4Attribute":"Man", "enemy5HP":3838 , "enemy5Class":"Saber", "enemy5Attribute":"Man","enemy6HP":3838 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":13332, "enemy7Class":"Saber", "enemy7Attribute":"Man", "enemy8HP":8232 , "enemy8Class":"Archer", "enemy8Attribute":"Man","enemy9HP":8232 , "enemy9Class":"Archer", "enemy9Attribute":"Man"},
{"id":13, "name":"Evil Bone: Unknown Coordinates X-G (Fuyuki) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Fuyuki#Unknown_Coordinates_X-G\" target=\"_blank\">wiki</a>}",
"enemy1HP":8667 , "enemy1Class":"Saber", "enemy1Attribute":"Man", "enemy2HP":9087 , "enemy2Class":"Saber", "enemy2Attribute":"Man", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":9177 , "enemy4Class":"Lancer", "enemy4Attribute":"Man", "enemy5HP":3838 , "enemy5Class":"Archer", "enemy5Attribute":"Man","enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":8753 , "enemy7Class":"Lancer", "enemy7Attribute":"Man", "enemy8HP":8753, "enemy8Class":"Lancer", "enemy8Attribute":"Man","enemy9HP":10388 , "enemy9Class":"Lancer", "enemy9Attribute":"Man"},
{"id":14, "name":"Dragon Fang: Deming (E Pluribus Unum) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_E_Pluribus_Unum#Deming\" target=\"_blank\">wiki</a>}",
"enemy1HP":12869 , "enemy1Class":"Rider", "enemy1Attribute":"Earth", "enemy2HP":12869 , "enemy2Class":"Rider", "enemy2Attribute":"Earth", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":24806 , "enemy4Class":"Rider", "enemy4Attribute":"Earth", "enemy5HP":20320 , "enemy5Class":"Rider", "enemy5Attribute":"Earth", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":49859 , "enemy7Class":"Rider", "enemy7Attribute":"Earth", "enemy8HP":109641 , "enemy8Class":"Rider", "enemy8Attribute":"Earth", "enemy9HP":49859 , "enemy9Class":"Rider", "enemy9Attribute":"Earth"},
{"id":15, "name":"Void's Dust: Charlotte (E Pluribus Unum) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_E_Pluribus_Unum#Charlotte\" target=\"_blank\">wiki</a>}",
"enemy1HP":17052 , "enemy1Class":"Caster", "enemy1Attribute":"Man", "enemy2HP":17052 , "enemy2Class":"Archer", "enemy2Attribute":"Man", "enemy3HP":17052 , "enemy3Class":"Archer", "enemy3Attribute":"Man",
"enemy4HP":37332 , "enemy4Class":"Lancer", "enemy4Attribute":"Man", "enemy5HP":46802 , "enemy5Class":"Berserker", "enemy5Attribute":"Man","enemy6HP":50193 , "enemy6Class":"Berserker", "enemy6Attribute":"Man",
"enemy7HP":38556 , "enemy7Class":"Lancer", "enemy7Attribute":"Man", "enemy8HP":103775 , "enemy8Class":"Berserker", "enemy8Attribute":"Man","enemy9HP":103138 , "enemy9Class":"Lancer", "enemy9Attribute":"Man"},
{"id":16, "name":"Fool's Chain: Wastelands of Death (Camelot) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Camelot#Wilderness_of_Death\" target=\"_blank\">wiki</a>}",
"enemy1HP":15594 , "enemy1Class":"Assassin", "enemy1Attribute":"Man", "enemy2HP":15594 , "enemy2Class":"Assassin", "enemy2Attribute":"Man", "enemy3HP":15594 , "enemy3Class":"Assassin", "enemy3Attribute":"Man",
"enemy4HP":23464 , "enemy4Class":"Assassin", "enemy4Attribute":"Man", "enemy5HP":48600 , "enemy5Class":"Berserker", "enemy5Attribute":"Man", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":93312 , "enemy7Class":"Berserker", "enemy7Attribute":"Man", "enemy8HP":87091 , "enemy8Class":"Berserker", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":17, "name":"Deadly Poisonous Needle: Field of Reeds (Babylonia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Babylonia#Phragmites_Prairie_.2F_Field_of_Reeds\" target=\"_blank\">wiki</a>}",
"enemy1HP":28764 , "enemy1Class":"Lancer", "enemy1Attribute":"Earth", "enemy2HP":28764 , "enemy2Class":"Lancer", "enemy2Attribute":"Earth", "enemy3HP":28764 , "enemy3Class":"Lancer", "enemy3Attribute":"Earth",
"enemy4HP":37864 , "enemy4Class":"Lancer", "enemy4Attribute":"Earth", "enemy5HP":37864 , "enemy5Class":"Lancer", "enemy5Attribute":"Earth", "enemy6HP":37864 , "enemy6Class":"Lancer", "enemy6Attribute":"Earth",
"enemy7HP":122015 , "enemy7Class":"Lancer", "enemy7Attribute":"Earth", "enemy8HP":86034 , "enemy8Class":"Lancer", "enemy8Attribute":"Earth", "enemy9HP":86034 , "enemy9Class":"Lancer", "enemy9Attribute":"Earth"},
{"id":18, "name":"Mystic Spinal Fluid: Shinjuku Station (Shinjuku) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Shinjuku#Shinjuku_Station\" target=\"_blank\">wiki</a>}",
"enemy1HP":24225 , "enemy1Class":"Archer", "enemy1Attribute":"Man", "enemy2HP":13867 , "enemy2Class":"Archer", "enemy2Attribute":"Man", "enemy3HP":13867 , "enemy3Class":"Archer", "enemy3Attribute":"Man",
"enemy4HP":17991 , "enemy4Class":"Archer", "enemy4Attribute":"Man", "enemy5HP":17991 , "enemy5Class":"Archer", "enemy5Attribute":"Man", "enemy6HP":30937 , "enemy6Class":"Archer", "enemy6Attribute":"Man",
"enemy7HP":92977 , "enemy7Class":"Archer", "enemy7Attribute":"Man", "enemy8HP":115889 , "enemy8Class":"Archer", "enemy8Attribute":"Man", "enemy9HP":92977 , "enemy9Class":"Archer", "enemy9Attribute":"Man"},
{"id":19, "name":"Stake of Wailing Night: Gallows Hill (Salem) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Salem#Gallow_Hill\" target=\"_blank\">wiki</a>}",
"enemy1HP":11866 , "enemy1Class":"Berserker", "enemy1Attribute":"Earth", "enemy2HP":13077 , "enemy2Class":"Berserker", "enemy2Attribute":"Earth", "enemy3HP":13057 , "enemy3Class":"Berserker", "enemy3Attribute":"Earth",
"enemy4HP":38912 , "enemy4Class":"Assassin", "enemy4Attribute":"Earth", "enemy5HP":15206 , "enemy5Class":"Berserker", "enemy5Attribute":"Earth", "enemy6HP":16695 , "enemy6Class":"Berserker", "enemy6Attribute":"Earth",
"enemy7HP":46866 , "enemy7Class":"Berserker", "enemy7Attribute":"Earth", "enemy8HP":192012 , "enemy8Class":"Assassin", "enemy8Attribute":"Earth", "enemy9HP":51180 , "enemy9Class":"Assassin", "enemy9Attribute":"Earth"},
{"id":20, "name":"Mystic Gunpowder: Yaga Smolensk (Anastasia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Anastasia#Yaga_Smolensk\" target=\"_blank\">wiki</a>}",
"enemy1HP":16923 , "enemy1Class":"Saber", "enemy1Attribute":"Earth", "enemy2HP":16732 , "enemy2Class":"Assassin", "enemy2Attribute":"Earth", "enemy3HP":14847 , "enemy3Class":"Saber", "enemy3Attribute":"Earth",
"enemy4HP":25886 , "enemy4Class":"Saber", "enemy4Attribute":"Earth", "enemy5HP":26456 , "enemy5Class":"Saber", "enemy5Attribute":"Earth", "enemy6HP":16732 , "enemy6Class":"Assassin", "enemy6Attribute":"Earth",
"enemy7HP":160815 , "enemy7Class":"Saber", "enemy7Attribute":"Earth", "enemy8HP":45301 , "enemy8Class":"Assassin", "enemy8Attribute":"Earth", "enemy9HP":46995 , "enemy9Class":"Assassin", "enemy9Attribute":"Earth"},
{"id":21, "name":"Seed of Yggdrasil: Fallen Babylon (Babylonia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Babylonia#Abolished_Metropolis_Babylon\" target=\"_blank\">wiki</a>}",
"enemy1HP":16552 , "enemy1Class":"Rider", "enemy1Attribute":"Earth", "enemy2HP":16552 , "enemy2Class":"Rider", "enemy2Attribute":"Earth", "enemy3HP":16552 , "enemy3Class":"Rider", "enemy3Attribute":"Earth",
"enemy4HP":30300 , "enemy4Class":"Rider", "enemy4Attribute":"Earth", "enemy5HP":30300 , "enemy5Class":"Rider", "enemy5Attribute":"Earth", "enemy6HP":30300 , "enemy6Class":"Rider", "enemy6Attribute":"Earth",
"enemy7HP":92385 , "enemy7Class":"Rider", "enemy7Attribute":"Earth", "enemy8HP":79221 , "enemy8Class":"Rider", "enemy8Attribute":"Earth", "enemy9HP":79221 , "enemy9Class":"Rider", "enemy9Attribute":"Earth"},
{"id":22, "name":"Ghost Lantern: Kutha (Babylonia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Babylonia#Cuthah\" target=\"_blank\">wiki</a>}",
"enemy1HP":20468 , "enemy1Class":"Assassin", "enemy1Attribute":"Sky", "enemy2HP":20468 , "enemy2Class":"Assassin", "enemy2Attribute":"Sky", "enemy3HP":27255 , "enemy3Class":"Assassin", "enemy3Attribute":"Sky",
"enemy4HP":43319 , "enemy4Class":"Assassin", "enemy4Attribute":"Sky", "enemy5HP":43319 , "enemy5Class":"Assassin", "enemy5Attribute":"Sky", "enemy6HP":66333 , "enemy6Class":"Assassin", "enemy6Attribute":"Sky",
"enemy7HP":273999 , "enemy7Class":"Assassin", "enemy7Attribute":"Sky", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":23, "name":"Octuplet Crystal: Peach Blossom Shangri-La (Agartha) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Agartha#Peach_Blossom_Spring\" target=\"_blank\">wiki</a>}",
"enemy1HP":16656 , "enemy1Class":"Berserker", "enemy1Attribute":"Sky", "enemy2HP":17540 , "enemy2Class":"Berserker", "enemy2Attribute":"Sky", "enemy3HP":16656 , "enemy3Class":"Berserker", "enemy3Attribute":"Sky",
"enemy4HP":26500 , "enemy4Class":"Berserker", "enemy4Attribute":"Sky", "enemy5HP":25616 , "enemy5Class":"Berserker", "enemy5Attribute":"Sky", "enemy6HP":24172 , "enemy6Class":"Berserker", "enemy6Attribute":"Sky",
"enemy7HP":277318 , "enemy7Class":"Berserker", "enemy7Attribute":"Sky", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":24, "name":"Serpent Jewel: Chasm in the Earth (Agartha) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Agartha#Chasm_on_The_Ground\" target=\"_blank\">wiki</a>}",
"enemy1HP":13202 , "enemy1Class":"Caster", "enemy1Attribute":"Earth", "enemy2HP":12649 , "enemy2Class":"Caster", "enemy2Attribute":"Earth", "enemy3HP":12649 , "enemy3Class":"Caster", "enemy3Attribute":"Earth",
"enemy4HP":19644 , "enemy4Class":"Caster", "enemy4Attribute":"Earth", "enemy5HP":19644 , "enemy5Class":"Caster", "enemy5Attribute":"Earth", "enemy6HP":25665 , "enemy6Class":"Caster", "enemy6Attribute":"Earth",
"enemy7HP":68311 , "enemy7Class":"Caster", "enemy7Attribute":"Earth", "enemy8HP":232310 , "enemy8Class":"Caster", "enemy8Attribute":"Earth", "enemy9HP":68311 , "enemy9Class":"Caster", "enemy9Attribute":"Earth"},
{"id":25, "name":"Phoenix Feather: Town Hall (Salem) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Salem#Town_Hall\" target=\"_blank\">wiki</a>}",
"enemy1HP":22291 , "enemy1Class":"Caster", "enemy1Attribute":"Earth", "enemy2HP":21738 , "enemy2Class":"Caster", "enemy2Attribute":"Earth", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":40932 , "enemy4Class":"Caster", "enemy4Attribute":"Earth", "enemy5HP":29722 , "enemy5Class":"Caster", "enemy5Attribute":"Earth", "enemy6HP":29722 , "enemy6Class":"Caster", "enemy6Attribute":"Earth",
"enemy7HP":85551 , "enemy7Class":"Caster", "enemy7Attribute":"Earth", "enemy8HP":176556 , "enemy8Class":"Caster", "enemy8Attribute":"Earth", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":26, "name":"Eternal Gear: Barrel Tower (Shinjuku) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Shinjuku#Barrel_Tower\" target=\"_blank\">wiki</a>}",
"enemy1HP":11457 , "enemy1Class":"Assassin", "enemy1Attribute":"Sky", "enemy2HP":18393 , "enemy2Class":"Assassin", "enemy2Attribute":"Sky", "enemy3HP":11457 , "enemy3Class":"Assassin", "enemy3Attribute":"Sky",
"enemy4HP":27204 , "enemy4Class":"Assassin", "enemy4Attribute":"Sky", "enemy5HP":32474 , "enemy5Class":"Assassin", "enemy5Attribute":"Sky", "enemy6HP":27204 , "enemy6Class":"Assassin", "enemy6Attribute":"Sky",
"enemy7HP":74846 , "enemy7Class":"Assassin", "enemy7Attribute":"Sky", "enemy8HP":74846 , "enemy8Class":"Assassin", "enemy8Attribute":"Sky", "enemy9HP":174084 , "enemy9Class":"Assassin", "enemy9Attribute":"Sky"},
{"id":27, "name":"Forbidden Page: Shinjuku 2-chome (Shinjuku) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Shinjuku#Shinjuku_2-chome\" target=\"_blank\">wiki</a>}",
"enemy1HP":16462 , "enemy1Class":"Caster", "enemy1Attribute":"Sky", "enemy2HP":19972 , "enemy2Class":"Caster", "enemy2Attribute":"Sky", "enemy3HP":19972 , "enemy3Class":"Caster", "enemy3Attribute":"Sky",
"enemy4HP":25847 , "enemy4Class":"Caster", "enemy4Attribute":"Sky", "enemy5HP":25847 , "enemy5Class":"Caster", "enemy5Attribute":"Sky", "enemy6HP":36680 , "enemy6Class":"Caster", "enemy6Attribute":"Sky",
"enemy7HP":262183 , "enemy7Class":"Archer", "enemy7Attribute":"Earth", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":28, "name":"Homunculus Baby: Whateley Residence (Salem) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Salem#Whateley_House\" target=\"_blank\">wiki</a>}",
"enemy1HP":10986 , "enemy1Class":"Lancer", "enemy1Attribute":"Sky", "enemy2HP":10986 , "enemy2Class":"Lancer", "enemy2Attribute":"Sky", "enemy3HP":11505 , "enemy3Class":"Lancer", "enemy3Attribute":"Sky",
"enemy4HP":20913 , "enemy4Class":"Lancer", "enemy4Attribute":"Sky", "enemy5HP":20913 , "enemy5Class":"Lancer", "enemy5Attribute":"Sky", "enemy6HP":24749 , "enemy6Class":"Lancer", "enemy6Attribute":"Sky",
"enemy7HP":64306 , "enemy7Class":"Lancer", "enemy7Attribute":"Sky", "enemy8HP":189802 , "enemy8Class":"Lancer", "enemy8Attribute":"Sky", "enemy9HP":64306 , "enemy9Class":"Lancer", "enemy9Attribute":"Sky"},
{"id":29, "name":"Meteor Horseshoe: Land of the Void (Camelot) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Camelot#Vast_Land_of_Nothingness\" target=\"_blank\">wiki</a>}",
"enemy1HP":11289 , "enemy1Class":"Rider", "enemy1Attribute":"Earth", "enemy2HP":11289 , "enemy2Class":"Rider", "enemy2Attribute":"Earth", "enemy3HP":11524 , "enemy3Class":"Archer", "enemy3Attribute":"Earth",
"enemy4HP":52224 , "enemy4Class":"Rider", "enemy4Attribute":"Earth", "enemy5HP":51680 , "enemy5Class":"Assassin", "enemy5Attribute":"Earth", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":72864 , "enemy7Class":"Rider", "enemy7Attribute":"Earth", "enemy8HP":72864 , "enemy8Class":"Rider", "enemy8Attribute":"Earth", "enemy9HP":124656 , "enemy9Class":"Lancer", "enemy9Attribute":"Earth"},
{"id":30, "name":"Great Knight Medal: Royal Castle (Camelot) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Camelot#Sovereign_Castle\" target=\"_blank\">wiki</a>}",
"enemy1HP":72538 , "enemy1Class":"Saber", "enemy1Attribute":"Man", "enemy2HP":72538 , "enemy2Class":"Saber", "enemy2Attribute":"Man", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":76356 , "enemy4Class":"Saber", "enemy4Attribute":"Man", "enemy5HP":76356 , "enemy5Class":"Saber", "enemy5Attribute":"Man", "enemy6HP":76356 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":204096 , "enemy7Class":"Saber", "enemy7Attribute":"Earth", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":31, "name":"Shell of Reminiscence: Observatory (Babylonia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Babylonia#Observatory\" target=\"_blank\">wiki</a>}",
"enemy1HP":17847 , "enemy1Class":"Saber", "enemy1Attribute":"Earth", "enemy2HP":17847 , "enemy2Class":"Saber", "enemy2Attribute":"Earth", "enemy3HP":23219 , "enemy3Class":"Saber", "enemy3Attribute":"Earth",
"enemy4HP":21379 , "enemy4Class":"Saber", "enemy4Attribute":"Earth", "enemy5HP":36220 , "enemy5Class":"Saber", "enemy5Attribute":"Earth", "enemy6HP":36220 , "enemy6Class":"Saber", "enemy6Attribute":"Earth",
"enemy7HP":118033 , "enemy7Class":"Saber", "enemy7Attribute":"Earth", "enemy8HP":187708 , "enemy8Class":"Saber", "enemy8Attribute":"Earth", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":32, "name":"Refined Magatama: Castle Town (Shimosa) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Shimosa#Castle_Town\" target=\"_blank\">wiki</a>}",
"enemy1HP":26978 , "enemy1Class":"Saber", "enemy1Attribute":"Sky", "enemy2HP":24467 , "enemy2Class":"Sky", "enemy2Attribute":"Saber", "enemy3HP":24467 , "enemy3Class":"Saber", "enemy3Attribute":"Sky",
"enemy4HP":37051 , "enemy4Class":"Saber", "enemy4Attribute":"Sky", "enemy5HP":39210 , "enemy5Class":"Sky", "enemy5Attribute":"Saber", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":54413 , "enemy7Class":"Saber", "enemy7Attribute":"Sky", "enemy8HP":54413 , "enemy8Class":"Sky", "enemy8Attribute":"Saber", "enemy9HP":196041 , "enemy9Class":"Saber", "enemy9Attribute":"Sky"},
{"id":33, "name":"Eternal Ice: Yaga Moscow (Anastasia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Anastasia#Yaga_Moscow\" target=\"_blank\">wiki</a>}",
"enemy1HP":28871 , "enemy1Class":"Assassin", "enemy1Attribute":"Man", "enemy2HP":25897 , "enemy2Class":"Assassin", "enemy2Attribute":"Man", "enemy3HP":25227 , "enemy3Class":"Assassin", "enemy3Attribute":"Man",
"enemy4HP":32245 , "enemy4Class":"Assassin", "enemy4Attribute":"Man", "enemy5HP":30233 , "enemy5Class":"Assassin", "enemy5Attribute":"Man", "enemy6HP":31331 , "enemy6Class":"Assassin", "enemy6Attribute":"Man",
"enemy7HP":51500 , "enemy7Class":"Assassin", "enemy7Attribute":"Man", "enemy8HP":50274 , "enemy8Class":"Assassin", "enemy8Attribute":"Man", "enemy9HP":168434 , "enemy9Class":"Assassin", "enemy9Attribute":"Man"},
{"id":34, "name":"Giant's Ring: Giant's Flower Patio (Gotterdammerung) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_G%C3%B6tterd%C3%A4mmerung#Giants.27_Flower_Patio\" target=\"_blank\">wiki</a>}",
"enemy1HP":21819 , "enemy1Class":"Berserker", "enemy1Attribute":"Earth", "enemy2HP":24771 , "enemy2Class":"Berserker", "enemy2Attribute":"Earth", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":31821 , "enemy4Class":"Berserker", "enemy4Attribute":"Earth", "enemy5HP":33774 , "enemy5Class":"Berserker", "enemy5Attribute":"Earth", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":51431 , "enemy7Class":"Berserker", "enemy7Attribute":"Earth", "enemy8HP":152001 , "enemy8Class":"Berserker", "enemy8Attribute":"Earth", "enemy9HP":53401 , "enemy9Class":"Berserker", "enemy9Attribute":"Earth"},
{"id":35, "name":"Aurora Steel: Castle of Ice and Snow (Gotterdammerung) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_G%C3%B6tterd%C3%A4mmerung#Castle_of_Ice_and_Snow\" target=\"_blank\">wiki</a>}",
"enemy1HP":9884 , "enemy1Class":"Rider", "enemy1Attribute":"Sky", "enemy2HP":10889 , "enemy2Class":"Rider", "enemy2Attribute":"Sky", "enemy3HP":10644 , "enemy3Class":"Rider", "enemy3Attribute":"Sky",
"enemy4HP":30279 , "enemy4Class":"Rider", "enemy4Attribute":"Sky", "enemy5HP":24599 , "enemy5Class":"Rider", "enemy5Attribute":"Sky", "enemy6HP":33264 , "enemy6Class":"Rider", "enemy6Attribute":"Sky",
"enemy7HP":41136 , "enemy7Class":"Rider", "enemy7Attribute":"Sky", "enemy8HP":49586 , "enemy8Class":"Rider", "enemy8Attribute":"Sky", "enemy9HP":180432 , "enemy9Class":"Rider", "enemy9Attribute":"Sky"},
{"id":36, "name":"Ancient Bell of Tranquility: Eight Gates Cave (Qin) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_S_I_N#Eight_Gates_Cave\" target=\"_blank\">wiki</a>}",
"enemy1HP":20232 , "enemy1Class":"Assassin", "enemy1Attribute":"Man", "enemy2HP":17588 , "enemy2Class":"Assassin", "enemy2Attribute":"Man", "enemy3HP":17588 , "enemy3Class":"Assassin", "enemy3Attribute":"Man",
"enemy4HP":24524 , "enemy4Class":"Assassin", "enemy4Attribute":"Man", "enemy5HP":26132 , "enemy5Class":"Assassin", "enemy5Attribute":"Man", "enemy6HP":25060 , "enemy6Class":"Assassin", "enemy6Attribute":"Man",
"enemy7HP":47607 , "enemy7Class":"Assassin", "enemy7Attribute":"Man", "enemy8HP":44207 , "enemy8Class":"Assassin", "enemy8Attribute":"Man", "enemy9HP":183480 , "enemy9Class":"Assassin", "enemy9Attribute":"Man"},
{"id":37, "name":"Arrowhead of Disasterous Sin: Remains of the Divine Floating Rock (Yuga Kshetra) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Yuga_Kshetra#Remains_of_the_Divine_Floating_Rock\" target=\"_blank\">wiki</a>}",
"enemy1HP":24889 , "enemy1Class":"Berserker", "enemy1Attribute":"Earth", "enemy2HP":24240 , "enemy2Class":"Berserker", "enemy2Attribute":"Earth", "enemy3HP":23591 , "enemy3Class":"Berserker", "enemy3Attribute":"Earth",
"enemy4HP":34617 , "enemy4Class":"Berserker", "enemy4Attribute":"Earth", "enemy5HP":33872 , "enemy5Class":"Berserker", "enemy5Attribute":"Earth", "enemy6HP":35363 , "enemy6Class":"Berserker", "enemy6Attribute":"Earth",
"enemy7HP":58118 , "enemy7Class":"Berserker", "enemy7Attribute":"Earth", "enemy8HP":107374 , "enemy8Class":"Berserker", "enemy8Attribute":"Earth", "enemy9HP":56902 , "enemy9Class":"Berserker", "enemy9Attribute":"Earth"},
{"id":38, "name":"Moonlit Tiara: Thanatos Island (Atlantis) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Atlantis#Thanatos_Island\" target=\"_blank\">wiki</a>}",
"enemy1HP":30903 , "enemy1Class":"Berserker", "enemy1Attribute":"Man", "enemy2HP":32078 , "enemy2Class":"Saber", "enemy2Attribute":"Man", "enemy3HP":30104 , "enemy3Class":"Assassin", "enemy3Attribute":"Man",
"enemy4HP":43286 , "enemy4Class":"Assassin", "enemy4Attribute":"Man", "enemy5HP":42648 , "enemy5Class":"Berserker", "enemy5Attribute":"Man", "enemy6HP":54964 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":60862 , "enemy7Class":"Saber", "enemy7Attribute":"Man", "enemy8HP":51840 , "enemy8Class":"Assassin", "enemy8Attribute":"Man", "enemy9HP":51440 , "enemy9Class":"Berserker", "enemy9Attribute":"Man"},
{"id":39, "name":"Divine Spirit Particle: Underground Organization Region - Outer Circumference (Olympus) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Olympus#Underground_Organization_Region:_Outer_Circumference\" target=\"_blank\">wiki</a>}",
"enemy1HP":42989 , "enemy1Class":"Assassin", "enemy1Attribute":"Sky", "enemy2HP":37263 , "enemy2Class":"Assassin", "enemy2Attribute":"Sky", "enemy3HP":30704 , "enemy3Class":"Assassin", "enemy3Attribute":"Sky",
"enemy4HP":53385 , "enemy4Class":"Assassin", "enemy4Attribute":"Sky", "enemy5HP":44202 , "enemy5Class":"Assassin", "enemy5Attribute":"Sky", "enemy6HP":37190 , "enemy6Class":"Assassin", "enemy6Attribute":"Sky",
"enemy7HP":42996 , "enemy7Class":"Assassin", "enemy7Attribute":"Sky", "enemy8HP":51794 , "enemy8Class":"Assassin", "enemy8Attribute":"Sky", "enemy9HP":61543 , "enemy9Class":"Assassin", "enemy9Attribute":"Sky"},
{"id":40, "name":"Claw of Chaos: Des Moines (E Pluribus Unum) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_E_Pluribus_Unum#Des_Moines\" target=\"_blank\">wiki</a>}",
"enemy1HP":20588 , "enemy1Class":"Assassin", "enemy1Attribute":"Earth", "enemy2HP":20588 , "enemy2Class":"Assassin", "enemy2Attribute":"Earth", "enemy3HP":20588 , "enemy3Class":"Assassin", "enemy3Attribute":"Earth",
"enemy4HP":127575 , "enemy4Class":"Berserker", "enemy4Attribute":"Earth", "enemy5HP":0 , "enemy5Class":"Saber", "enemy5Attribute":"Man", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":148656 , "enemy7Class":"Lancer", "enemy7Attribute":"Man", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":41, "name":"Heart of the Foreign God: Carter Residence (Salem) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Salem#Carter_House\" target=\"_blank\">wiki</a>}",
"enemy1HP":30685 , "enemy1Class":"Assassin", "enemy1Attribute":"Earth", "enemy2HP":35865 , "enemy2Class":"Assassin", "enemy2Attribute":"Earth", "enemy3HP":30685 , "enemy3Class":"Assassin", "enemy3Attribute":"Earth",
"enemy4HP":40944 , "enemy4Class":"Assassin", "enemy4Attribute":"Earth", "enemy5HP":38912 , "enemy5Class":"Assassin", "enemy5Attribute":"Earth", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":199841 , "enemy7Class":"Caster", "enemy7Attribute":"Sky", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":42, "name":"Dragon's Reverse Scale: Nippur (Babylonia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Babylonia#Nippur\" target=\"_blank\">wiki</a>}",
"enemy1HP":25169 , "enemy1Class":"Lancer", "enemy1Attribute":"Earth", "enemy2HP":25169 , "enemy2Class":"Lancer", "enemy2Attribute":"Earth", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":39137 , "enemy4Class":"Lancer", "enemy4Attribute":"Earth", "enemy5HP":39137 , "enemy5Class":"Lancer", "enemy5Attribute":"Earth", "enemy6HP":39137 , "enemy6Class":"Lancer", "enemy6Attribute":"Earth",
"enemy7HP":288970 , "enemy7Class":"Rider", "enemy7Attribute":"Earth", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":43, "name":"Spirit Root: Holy City (Camelot) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Camelot#Holy_City_Districts\" target=\"_blank\">wiki</a>}",
"enemy1HP":23760 , "enemy1Class":"Berserker", "enemy1Attribute":"Sky", "enemy2HP":11781 , "enemy2Class":"Lancer", "enemy2Attribute":"Man", "enemy3HP":11781 , "enemy3Class":"Lancer", "enemy3Attribute":"Man",
"enemy4HP":26730 , "enemy4Class":"Berserker", "enemy4Attribute":"Sky", "enemy5HP":26730 , "enemy5Class":"Berserker", "enemy5Attribute":"Sky", "enemy6HP":13901 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":236087 , "enemy7Class":"Saber", "enemy7Attribute":"Earth", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":44, "name":"Warhorse's Young Horn: Initiate Point (Yuga Ksehtra) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Yuga_Kshetra#Initiate_Point\" target=\"_blank\">wiki</a>}",
"enemy1HP":25844 , "enemy1Class":"Berserker", "enemy1Attribute":"Earth", "enemy2HP":25844 , "enemy2Class":"Berserker", "enemy2Attribute":"Earth", "enemy3HP":20368 , "enemy3Class":"Berserker", "enemy3Attribute":"Earth",
"enemy4HP":30989 , "enemy4Class":"Berserker", "enemy4Attribute":"Earth", "enemy5HP":52165 , "enemy5Class":"Lancer", "enemy5Attribute":"Sky", "enemy6HP":30291 , "enemy6Class":"Berserker", "enemy6Attribute":"Earth",
"enemy7HP":77177 , "enemy7Class":"Lancer", "enemy7Attribute":"Sky", "enemy8HP":104549 , "enemy8Class":"Lancer", "enemy8Attribute":"Sky", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":45, "name":"(NA) Warhorse's Young Horn: Campsite (Agartha) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Agartha#Campsite\" target=\"_blank\">wiki</a>}",
"enemy1HP":11550 , "enemy1Class":"Lancer", "enemy1Attribute":"Man", "enemy2HP":11359 , "enemy2Class":"Lancer", "enemy2Attribute":"Man", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":25803 , "enemy4Class":"Lancer", "enemy4Attribute":"Man", "enemy5HP":13697 , "enemy5Class":"Lancer", "enemy5Attribute":"Man", "enemy6HP":13697 , "enemy6Class":"Lancer", "enemy6Attribute":"Man",
"enemy7HP":58828 , "enemy7Class":"Lancer", "enemy7Attribute":"Man", "enemy8HP":32378 , "enemy8Class":"Lancer", "enemy8Attribute":"Man", "enemy9HP":254518 , "enemy9Class":"Lancer", "enemy9Attribute":"Earth"},
{"id":46, "name":"Tearstone of Blood: Shinjuku 2-Chome (Shinjuku) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Shinjuku#Shinjuku_2-chome\" target=\"_blank\">wiki</a>}",
"enemy1HP":16462 , "enemy1Class":"Caster", "enemy1Attribute":"Sky", "enemy2HP":19972 , "enemy2Class":"Caster", "enemy2Attribute":"Sky", "enemy3HP":19972 , "enemy3Class":"Caster", "enemy3Attribute":"Sky",
"enemy4HP":25847 , "enemy4Class":"Caster", "enemy4Attribute":"Sky", "enemy5HP":25847 , "enemy5Class":"Caster", "enemy5Attribute":"Sky", "enemy6HP":36680 , "enemy6Class":"Caster", "enemy6Attribute":"Sky",
"enemy7HP":262183 , "enemy7Class":"Archer", "enemy7Attribute":"Earth", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":47, "name":"Black Beast Grease: Northern Cliffs (Agartha) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Agartha#Northern_Palisade\" target=\"_blank\">wiki</a>}",
"enemy1HP":23988 , "enemy1Class":"Assassin", "enemy1Attribute":"Man", "enemy2HP":23988 , "enemy2Class":"Assassin", "enemy2Attribute":"Man", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":38953 , "enemy4Class":"Assassin", "enemy4Attribute":"Man", "enemy5HP":43410 , "enemy5Class":"Assassin", "enemy5Attribute":"Man", "enemy6HP":38953 , "enemy6Class":"Assassin", "enemy6Attribute":"Man",
"enemy7HP":266255 , "enemy7Class":"Assassin", "enemy7Attribute":"Earth", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":48, "name":"(JP) Black Beast Grease: Secluded Grotto (Yuga Ksehtra) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Yuga_Kshetra#Secluded_Grotto\" target=\"_blank\">wiki</a>}",
"enemy1HP":19880 , "enemy1Class":"Berserker", "enemy1Attribute":"Earth", "enemy2HP":20410 , "enemy2Class":"Berserker", "enemy2Attribute":"Earth", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":33501 , "enemy4Class":"Berserker", "enemy4Attribute":"Earth", "enemy5HP":47073 , "enemy5Class":"Assassin", "enemy5Attribute":"Sky", "enemy6HP":33501 , "enemy6Class":"Berserker", "enemy6Attribute":"Earth",
"enemy7HP":106893 , "enemy7Class":"Assassin", "enemy7Attribute":"Sky", "enemy8HP":45062 , "enemy8Class":"Berserker", "enemy8Attribute":"Earth", "enemy9HP":70991 , "enemy9Class":"Assassin", "enemy9Attribute":"Sky"},
{"id":49, "name":"Lamp of Evil Sealing: Jail (Salem) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Salem#Jail\" target=\"_blank\">wiki</a>}",
"enemy1HP":10879 , "enemy1Class":"Saber", "enemy1Attribute":"Earth", "enemy2HP":11135 , "enemy2Class":"Saber", "enemy2Attribute":"Earth", "enemy3HP":10879 , "enemy3Class":"Saber", "enemy3Attribute":"Earth",
"enemy4HP":15531 , "enemy4Class":"Saber", "enemy4Attribute":"Earth", "enemy5HP":15531 , "enemy5Class":"Saber", "enemy5Attribute":"Earth", "enemy6HP":15873 , "enemy6Class":"Saber", "enemy6Attribute":"Earth",
"enemy7HP":49820 , "enemy7Class":"Saber", "enemy7Attribute":"Earth", "enemy8HP":196767 , "enemy8Class":"Caster", "enemy8Attribute":"Earth", "enemy9HP":49820 , "enemy9Class":"Saber", "enemy9Attribute":"Earth"},
{"id":50, "name":"Scarab of Wisdom: Great Temple (Camelot) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Camelot#Great_Temple\" target=\"_blank\">wiki</a>}",
"enemy1HP":14337 , "enemy1Class":"Berserker", "enemy1Attribute":"Man", "enemy2HP":11010 , "enemy2Class":"Assassin", "enemy2Attribute":"Man", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":20071 , "enemy4Class":"Berserker", "enemy4Attribute":"Man", "enemy5HP":20071 , "enemy5Class":"Berserker", "enemy5Attribute":"Man", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":197521 , "enemy7Class":"Caster", "enemy7Attribute":"Earth", "enemy8HP":183173 , "enemy8Class":"Caster", "enemy8Attribute":"Earth", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":51, "name":"(JP) Scarab of Wisdom: Deimos Island (Atlantis) {WARNING! This quest has special effects, please check <a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Atlantis#Deimos_Island\" target=\"_blank\">wiki</a>}",
"enemy1HP":27755 , "enemy1Class":"Saber", "enemy1Attribute":"Man", "enemy2HP":27755 , "enemy2Class":"Saber", "enemy2Attribute":"Man", "enemy3HP":29620 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":31009 , "enemy4Class":"Saber", "enemy4Attribute":"Man", "enemy5HP":67256 , "enemy5Class":"Caster", "enemy5Attribute":"Earth", "enemy6HP":31009 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":88435 , "enemy7Class":"Caster", "enemy7Attribute":"Earth", "enemy8HP":34077 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":34077 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":52, "name":"Primodial Lanugo: Blood Fort (Babylonia) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Babylonia#Blood_Fort_Andromeda\" target=\"_blank\">wiki</a>}",
"enemy1HP":19243 , "enemy1Class":"Rider", "enemy1Attribute":"Earth", "enemy2HP":19243 , "enemy2Class":"Rider", "enemy2Attribute":"Earth", "enemy3HP":19243 , "enemy3Class":"Rider", "enemy3Attribute":"Earth",
"enemy4HP":182476 , "enemy4Class":"Rider", "enemy4Attribute":"Earth", "enemy5HP":254016 , "enemy5Class":"Rider", "enemy5Attribute":"Earth", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":0 , "enemy7Class":"Saber", "enemy7Attribute":"Man", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":53, "name":"Cursed Beast Gallstone: Arakawa Prairie (Shimosa) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Shimosa#Arakawa_Prairie\" target=\"_blank\">wiki</a>}",
"enemy1HP":23831 , "enemy1Class":"Saber", "enemy1Attribute":"Sky", "enemy2HP":23831 , "enemy2Class":"Saber", "enemy2Attribute":"Sky", "enemy3HP":24506 , "enemy3Class":"Saber", "enemy3Attribute":"Sky",
"enemy4HP":108207 , "enemy4Class":"Berserker", "enemy4Attribute":"Earth", "enemy5HP":0 , "enemy5Class":"Saber", "enemy5Attribute":"Man", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":38130 , "enemy7Class":"Saber", "enemy7Attribute":"Sky", "enemy8HP":152815 , "enemy8Class":"Sky", "enemy8Attribute":"Rider", "enemy9HP":38130 , "enemy9Class":"Saber", "enemy9Attribute":"Sky"},
{"id":54, "name":"Mysterious Divine Wine: Palace of Dragon King (Agartha) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Agartha#Palace_of_the_Dragon_King\" target=\"_blank\">wiki</a>}",
"enemy1HP":10055 , "enemy1Class":"Rider", "enemy1Attribute":"Man", "enemy2HP":10055 , "enemy2Class":"Rider", "enemy2Attribute":"Man", "enemy3HP":10451 , "enemy3Class":"Rider", "enemy3Attribute":"Man",
"enemy4HP":11955 , "enemy4Class":"Rider", "enemy4Attribute":"Man", "enemy5HP":11015 , "enemy5Class":"Rider", "enemy5Attribute":"Man", "enemy6HP":11015 , "enemy6Class":"Rider", "enemy6Attribute":"Man",
"enemy7HP":344794 , "enemy7Class":"Archer", "enemy7Attribute":"Earth", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":55, "name":"Dawnlight Reactor Core: Detention Centre (Qin) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_S_I_N#Detention_Centre\" target=\"_blank\">wiki</a>}",
"enemy1HP":16342 , "enemy1Class":"Assassin", "enemy1Attribute":"Man", "enemy2HP":15136 , "enemy2Class":"Assassin", "enemy2Attribute":"Man", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":20141 , "enemy4Class":"Assassin", "enemy4Attribute":"Man", "enemy5HP":20141 , "enemy5Class":"Assassin", "enemy5Attribute":"Man", "enemy6HP":50502 , "enemy6Class":"Archer", "enemy6Attribute":"Sky",
"enemy7HP":80684 , "enemy7Class":"Archer", "enemy7Attribute":"Sky", "enemy8HP":178837 , "enemy8Class":"Archer", "enemy8Attribute":"Sky", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":56, "name":"Tsukumo Mirror: Trembling in Fear (Shimosa) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Shimosa#Hill_Behind_The_Hermitage\" target=\"_blank\">wiki</a>}",
"enemy1HP":30627 , "enemy1Class":"Assassin", "enemy1Attribute":"Sky", "enemy2HP":31565 , "enemy2Class":"Assassin", "enemy2Attribute":"Sky", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":42490 , "enemy4Class":"Assassin", "enemy4Attribute":"Sky", "enemy5HP":34379 , "enemy5Class":"Assassin", "enemy5Attribute":"Sky", "enemy6HP":32503 , "enemy6Class":"Assassin", "enemy6Attribute":"Sky",
"enemy7HP":160487 , "enemy7Class":"Assassin", "enemy7Attribute":"Earth", "enemy8HP":70506 , "enemy8Class":"Assassin", "enemy8Attribute":"Sky", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":57, "name":"Egg of Truth: Deewar (Yuga Ksehtra) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Yuga_Kshetra#Dewar\" target=\"_blank\">wiki</a>}",
"enemy1HP":29820 , "enemy1Class":"Berserker", "enemy1Attribute":"Earth", "enemy2HP":29820 , "enemy2Class":"Berserker", "enemy2Attribute":"Earth", "enemy3HP":32058 , "enemy3Class":"Berserker", "enemy3Attribute":"Earth",
"enemy4HP":40201 , "enemy4Class":"Berserker", "enemy4Attribute":"Earth", "enemy5HP":39335 , "enemy5Class":"Berserker", "enemy5Attribute":"Earth", "enemy6HP":41067 , "enemy6Class":"Berserker", "enemy6Attribute":"Earth",
"enemy7HP":175857 , "enemy7Class":"Lancer", "enemy7Attribute":"Sky", "enemy8HP":0 , "enemy8Class":"Saber", "enemy8Attribute":"Man", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":58, "name":"Glittering Star Shard: Machine God's Cloister (Olympus) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Olympus#Machine_God.27s_Cloister\" target=\"_blank\">wiki</a>}",
"enemy1HP":30420 , "enemy1Class":"Caster", "enemy1Attribute":"Earth", "enemy2HP":31499 , "enemy2Class":"Caster", "enemy2Attribute":"Earth", "enemy3HP":30420 , "enemy3Class":"Caster", "enemy3Attribute":"Earth",
"enemy4HP":40391 , "enemy4Class":"Caster", "enemy4Attribute":"Earth", "enemy5HP":40391 , "enemy5Class":"Caster", "enemy5Attribute":"Earth", "enemy6HP":42421 , "enemy6Class":"Caster", "enemy6Attribute":"Earth",
"enemy7HP":51816 , "enemy7Class":"Caster", "enemy7Attribute":"Earth", "enemy8HP":126833 , "enemy8Class":"Rider", "enemy8Attribute":"Earth", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":59, "name":"Fruit of Eternity: Interstellar City East (Olympus) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Olympus#Interstellar_City:_East\" target=\"_blank\">wiki</a>}",
"enemy1HP":25243 , "enemy1Class":"Berserker", "enemy1Attribute":"Sky", "enemy2HP":35830 , "enemy2Class":"Berserker", "enemy2Attribute":"Sky", "enemy3HP":25754 , "enemy3Class":"Berserker", "enemy3Attribute":"Sky",
"enemy4HP":59955 , "enemy4Class":"Lancer", "enemy4Attribute":"Man", "enemy5HP":30306 , "enemy5Class":"Berserker", "enemy5Attribute":"Sky", "enemy6HP":30954 , "enemy6Class":"Berserker", "enemy6Attribute":"Sky",
"enemy7HP":40481 , "enemy7Class":"Berserker", "enemy7Attribute":"Sky", "enemy8HP":50164 , "enemy8Class":"Berserker", "enemy8Attribute":"Sky", "enemy9HP":74983 , "enemy9Class":"Lancer", "enemy9Attribute":"Man"},
{"id":60, "name":"Fruit of Eternity: Interstellar City West (Olympus)<b>Most AP/Drop for this mat</b> {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Olympus#Interstellar_City:_West\" target=\"_blank\">wiki</a>}",
"enemy1HP":51959 , "enemy1Class":"Lancer", "enemy1Attribute":"Sky", "enemy2HP":0 , "enemy2Class":"Saber", "enemy2Attribute":"Man", "enemy3HP":0 , "enemy3Class":"Saber", "enemy3Attribute":"Man",
"enemy4HP":100357 , "enemy4Class":"Lancer", "enemy4Attribute":"Man", "enemy5HP":0 , "enemy5Class":"Saber", "enemy5Attribute":"Man", "enemy6HP":0 , "enemy6Class":"Saber", "enemy6Attribute":"Man",
"enemy7HP":148570 , "enemy7Class":"Lancer", "enemy7Attribute":"Man", "enemy8HP":71735 , "enemy8Class":"Lancer", "enemy8Attribute":"Sky", "enemy9HP":0 , "enemy9Class":"Saber", "enemy9Attribute":"Man"},
{"id":61, "name":"Fruit of Eternity: Interstellar City South (Olympus) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Olympus#Interstellar_City:_South\" target=\"_blank\">wiki</a>}",
"enemy1HP":26296 , "enemy1Class":"Assassin", "enemy1Attribute":"Sky", "enemy2HP":27126 , "enemy2Class":"Assassin", "enemy2Attribute":"Sky", "enemy3HP":27126 , "enemy3Class":"Assassin", "enemy3Attribute":"Sky",
"enemy4HP":30212 , "enemy4Class":"Assassin", "enemy4Attribute":"Sky", "enemy5HP":70250 , "enemy5Class":"Lancer", "enemy5Attribute":"Man", "enemy6HP":31110 , "enemy6Class":"Assassin", "enemy6Attribute":"Sky",
"enemy7HP":90917 , "enemy7Class":"Lancer", "enemy7Attribute":"Man", "enemy8HP":35362 , "enemy8Class":"Assassin", "enemy8Attribute":"Sky", "enemy9HP":34397 , "enemy9Class":"Assassin", "enemy9Attribute":"Sky"},
{"id":62, "name": "Grand Nero Fest 2021 Rotation 3 90+ Node {<a href= \"https://fategrandorder.fandom.com/wiki/Grand_Nero_Fest_2021#Finals\" target=\"_blank\">wiki</a>}",
"enemy1HP": 66162, "enemy1Class": "Assassin","enemy1Attribute": "Sky","enemy2HP": 69013,"enemy2Class": "Assassin","enemy2Attribute": "Sky","enemy3HP": 0,"enemy3Class": "Saber","enemy3Attribute": "Man",
"enemy4HP": 0, "enemy4Class": "Saber","enemy4Attribute": "Man","enemy5HP": 138905,"enemy5Class": "Assassin","enemy5Attribute": "Earth","enemy6HP": 0,"enemy6Class": "Saber","enemy6Attribute": "Man",
"enemy7HP": 103987,"enemy7Class": "Assassin","enemy7Attribute": "Earth","enemy8HP": 172810,"enemy8Class": "Assassin","enemy8Attribute": "Man","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":63, "name": "Grand Nero Fest 2021 Rotation 3 90 Node {<a href= \"https://fategrandorder.fandom.com/wiki/Grand_Nero_Fest_2021#Finals\" target=\"_blank\">wiki</a>}",
"enemy1HP": 23301, "enemy1Class": "Caster","enemy1Attribute": "Sky","enemy2HP": 23301,"enemy2Class": "Caster","enemy2Attribute": "Sky","enemy3HP": 23465, "enemy3Class": "Caster","enemy3Attribute": "Sky",
"enemy4HP": 24319, "enemy4Class": "Caster","enemy4Attribute": "Sky","enemy5HP": 23465,"enemy5Class": "Caster", "enemy5Attribute": "Sky", "enemy6HP": 81857,"enemy6Class": "Caster","enemy6Attribute": "Sky",
"enemy7HP": 152662, "enemy7Class": "Caster","enemy7Attribute": "Sky","enemy8HP": 98090,"enemy8Class": "Saber","enemy8Attribute": "Man","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":64, "name": "Grand Nero Fest 2021 Rotation 2 90+ Node {<a href= \"https://fategrandorder.fandom.com/wiki/Grand_Nero_Fest_2021#Semis\" target=\"_blank\">wiki</a>}",
"enemy1HP": 0,"enemy1Class": "Saber","enemy1Attribute": "Man","enemy2HP": 67114,"enemy2Class": "Archer","enemy2Attribute": "Sky","enemy3HP": 0,"enemy3Class": "Saber","enemy3Attribute": "Man",
"enemy4HP": 132805,"enemy4Class": "Archer","enemy4Attribute": "Earth","enemy5HP": 68360,"enemy5Class": "Archer","enemy5Attribute": "Sky","enemy6HP": 0,"enemy6Class": "Saber","enemy6Attribute": "Man",
"enemy7HP": 101595,"enemy7Class": "Archer","enemy7Attribute": "Man","enemy8HP": 180307,"enemy8Class": "Archer","enemy8Attribute": "Sky","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":65, "name": "Grand Nero Fest 2021 Rotation 2 90 Node {<a href= \"https://fategrandorder.fandom.com/wiki/Grand_Nero_Fest_2021#Semis\" target=\"_blank\">wiki</a>}",
"enemy1HP": 16159,"enemy1Class": "Rider","enemy1Attribute": "Earth","enemy2HP": 16450,"enemy2Class": "Rider","enemy2Attribute": "Earth","enemy3HP": 18760,"enemy3Class": "Rider","enemy3Attribute": "Earth",
"enemy4HP": 18760,"enemy4Class": "Rider","enemy4Attribute": "Earth","enemy5HP": 73776,"enemy5Class": "Rider","enemy5Attribute": "Earth","enemy6HP": 0,"enemy6Class": "Saber","enemy6Attribute": "Man",
"enemy7HP": 160950,"enemy7Class": "Rider","enemy7Attribute": "Sky","enemy8HP": 72217,"enemy8Class": "Archer","enemy8Attribute": "Man","enemy9HP": 79832,"enemy9Class": "Caster","enemy9Attribute": "Earth"},
{"id":66, "name": "Grand Nero Fest 2021 Rotation 1 90 Node {<a href= \"https://fategrandorder.fandom.com/wiki/Grand_Nero_Fest_2021#Preliminaries\" target=\"_blank\">wiki</a>}",
"enemy1HP": 22136,"enemy1Class": "Archer","enemy1Attribute": "Earth","enemy2HP": 21168,"enemy2Class": "Archer","enemy2Attribute": "Earth","enemy3HP": 30949,"enemy3Class": "Archer","enemy3Attribute": "Earth",
"enemy4HP": 22136,"enemy4Class": "Archer","enemy4Attribute": "Earth","enemy5HP": 31779,"enemy5Class": "Archer","enemy5Attribute": "Earth","enemy6HP": 70748,"enemy6Class": "Archer","enemy6Attribute": "Earth",
"enemy7HP": 83331,"enemy7Class": "Ruler","enemy7Attribute": "Star","enemy8HP": 163943,"enemy8Class": "Archer","enemy8Attribute": "Man","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":67, "name": "Christmas 2020 90+ Ticket Node {<a href= \"https://fategrandorder.fandom.com/wiki/Christmas_2020#Free_Quest\" target=\"_blank\">wiki</a>}",
"enemy1HP": 81048,"enemy1Class": "Archer","enemy1Attribute": "Man","enemy2HP": 65295,"enemy2Class": "Archer","enemy2Attribute": "Man","enemy3HP": 0,"enemy3Class": "Saber","enemy3Attribute": "Man",
"enemy4HP": 0,"enemy4Class": "Saber","enemy4Attribute": "Man","enemy5HP": 112786,"enemy5Class": "Archer","enemy5Attribute": "Sky","enemy6HP": 0,"enemy6Class": "Saber","enemy6Attribute": "Man",
"enemy7HP": 75921,"enemy7Class": "Archer","enemy7Attribute": "Earth","enemy8HP": 176809,"enemy8Class": "Archer","enemy8Attribute": "Sky","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":68, "name": "Christmas 2020 90 Ticket Node {<a href= \"https://fategrandorder.fandom.com/wiki/Christmas_2020#Free_Quest\" target=\"_blank\">wiki</a>}",
"enemy1HP": 30199,"enemy1Class": "Lancer","enemy1Attribute": "Earth","enemy2HP": 28974,"enemy2Class": "Lancer","enemy2Attribute": "Earth","enemy3HP": 28551,"enemy3Class": "Lancer","enemy3Attribute": "Earth",
"enemy4HP": 30199,"enemy4Class": "Lancer","enemy4Attribute": "Earth","enemy5HP": 39297,"enemy5Class": "Lancer","enemy5Attribute": "Earth","enemy6HP": 81059,"enemy6Class": "Lancer","enemy6Attribute": "Earth",
"enemy7HP": 54951,"enemy7Class": "Lancer","enemy7Attribute": "Earth","enemy8HP": 53588,"enemy8Class": "Lancer","enemy8Attribute": "Earth","enemy9HP": 107096,"enemy9Class": "Lancer","enemy9Attribute": "Man"},
{"id":69, "name": "ScathachFest 2020 Rotation 3 90 Ticket node {<a href= \"https://fategrandorder.fandom.com/wiki/Dance_Tournament_in_the_Land_of_Shadows#Free_Quests\" target=\"_blank\">wiki</a>}",
"enemy1HP": 13858,"enemy1Class": "Berserker","enemy1Attribute": "Earth","enemy2HP": 20472,"enemy2Class": "Berserker","enemy2Attribute": "Earth","enemy3HP": 13564,"enemy3Class": "Berserker","enemy3Attribute": "Earth",
"enemy4HP": 81790,"enemy4Class": "Saber","enemy4Attribute": "Sky","enemy5HP": 30154,"enemy5Class": "Berserker","enemy5Attribute": "Earth","enemy6HP": 20870,"enemy6Class": "Berserker","enemy6Attribute": "Earth",
"enemy7HP": 108945,"enemy7Class": "Saber","enemy7Attribute": "Earth","enemy8HP": 160360,"enemy8Class": "Berserker","enemy8Attribute": "Earth","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":70, "name": "ScathachFest 2020 Rotation 3 90+ Ticket node {<a href= \"https://fategrandorder.fandom.com/wiki/Dance_Tournament_in_the_Land_of_Shadows#Free_Quests\" target=\"_blank\">wiki</a>}",
"enemy1HP": 0,"enemy1Class": "Saber","enemy1Attribute": "Man","enemy2HP": 69589,"enemy2Class": "Berserker","enemy2Attribute": "Earth","enemy3HP": 0,"enemy3Class": "Saber","enemy3Attribute": "Man",
"enemy4HP": 0,"enemy4Class": "Saber","enemy4Attribute": "Man","enemy5HP": 103897,"enemy5Class": "Saber","enemy5Attribute": "Sky","enemy6HP": 0,"enemy6Class": "Saber","enemy6Attribute": "Man",
"enemy7HP": 118600,"enemy7Class": "Lancer","enemy7Attribute": "Star","enemy8HP": 191280,"enemy8Class": "Lancer","enemy8Attribute": "Earth","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":71, "name": "ScathachFest 2020 Rotation 2 90+ Ticket node {<a href= \"https://fategrandorder.fandom.com/wiki/Dance_Tournament_in_the_Land_of_Shadows#Free_Quests\" target=\"_blank\">wiki</a>}",
"enemy1HP": 0,"enemy1Class": "Saber","enemy1Attribute": "Man","enemy2HP": 104641,"enemy2Class": "Assassin","enemy2Attribute": "Earth","enemy3HP": 0,"enemy3Class": "Saber","enemy3Attribute": "Man",
"enemy4HP": 31769,"enemy4Class": "Assassin","enemy4Attribute": "Man","enemy5HP": 22890,"enemy5Class": "Assassin","enemy5Attribute": "Man","enemy6HP": 23334,"enemy6Class": "Assassin","enemy6Attribute": "Man",
"enemy7HP": 201222,"enemy7Class": "Assassin","enemy7Attribute": "Man","enemy8HP": 121030,"enemy8Class": "Assassin","enemy8Attribute": "Star","enemy9HP": 0,"enemy9Class": "Assassin","enemy9Attribute": "Man"},
{"id":72, "name": "ScathachFest 2020 Rotation 2 90 Ticket node {<a href= \"https://fategrandorder.fandom.com/wiki/Dance_Tournament_in_the_Land_of_Shadows#Free_Quests\" target=\"_blank\">wiki</a>}",
"enemy1HP": 10596,"enemy1Class": "Lancer","enemy1Attribute": "Man","enemy2HP": 15219,"enemy2Class": "Lancer","enemy2Attribute": "Man","enemy3HP": 10786,"enemy3Class": "Lancer","enemy3Attribute": "Man",
"enemy4HP": 16752,"enemy4Class": "Lancer","enemy4Attribute": "Man","enemy5HP": 21132,"enemy5Class": "Lancer","enemy5Attribute": "Man","enemy6HP": 81886,"enemy6Class": "Lancer","enemy6Attribute": "Earth",
"enemy7HP": 160509,"enemy7Class": "Lancer","enemy7Attribute": "Sky","enemy8HP": 69091,"enemy8Class": "Lancer","enemy8Attribute": "Man","enemy9HP": 64714,"enemy9Class": "Lancer","enemy9Attribute": "Man"},
{"id":73, "name": "ScathachFest 2020 Rotation 1 90 Ticket node {<a href= \"https://fategrandorder.fandom.com/wiki/Dance_Tournament_in_the_Land_of_Shadows#Free_Quests\" target=\"_blank\">wiki</a>}",
"enemy1HP": 19884,"enemy1Class": "Lancer","enemy1Attribute": "Earth","enemy2HP": 13448,"enemy2Class": "Lancer","enemy2Attribute": "Man","enemy3HP": 13226,"enemy3Class": "Lancer","enemy3Attribute": "Man",
"enemy4HP": 80962,"enemy4Class": "Caster","enemy4Attribute": "Sky","enemy5HP": 35929,"enemy5Class": "Lancer","enemy5Attribute": "Earth","enemy6HP": 30312,"enemy6Class": "Lancer","enemy6Attribute": "Man",
"enemy7HP": 160380,"enemy7Class": "Caster","enemy7Attribute": "Sky","enemy8HP": 93054,"enemy8Class": "Lancer","enemy8Attribute": "Sky","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":74, "name": "ScathachFest 2020 Rotation 1 90+ Ticket node {<a href= \"https://fategrandorder.fandom.com/wiki/Dance_Tournament_in_the_Land_of_Shadows#Free_Quests\" target=\"_blank\">wiki</a>}",
"enemy1HP": 48936,"enemy1Class": "Rider","enemy1Attribute": "Earth","enemy2HP": 29402,"enemy2Class": "Rider","enemy2Attribute": "Sky","enemy3HP": 101895,"enemy3Class": "Saber","enemy3Attribute": "Man",
"enemy4HP": 0,"enemy4Class": "Saber","enemy4Attribute": "Man","enemy5HP": 101895,"enemy5Class": "Rider","enemy5Attribute": "Earth","enemy6HP": 0,"enemy6Class": "Saber","enemy6Attribute": "Man",
"enemy7HP": 201722,"enemy7Class": "Lancer","enemy7Attribute": "Sky","enemy8HP": 120082,"enemy8Class": "Lancer","enemy8Attribute": "Star","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":75, "name": "Galemas 2019 Best/Final Ticket Node {<a href= \"https://fategrandorder.fandom.com/wiki/Christmas_2019#Free_quest\" target=\"_blank\">wiki</a>}",
"enemy1HP": 24945,"enemy1Class": "Lancer","enemy1Attribute": "Sky","enemy2HP": 33371,"enemy2Class": "Lancer","enemy2Attribute": "Sky","enemy3HP": 24526,"enemy3Class": "Lancer","enemy3Attribute": "Sky",
"enemy4HP": 92001,"enemy4Class": "Lancer","enemy4Attribute": "Man","enemy5HP": 34015,"enemy5Class": "Lancer","enemy5Attribute": "Sky","enemy6HP": 21176,"enemy6Class": "Lancer","enemy6Attribute": "Sky",
"enemy7HP": 31308,"enemy7Class": "Lancer","enemy7Attribute": "Sky","enemy8HP": 151215,"enemy8Class": "Lancer","enemy8Attribute": "Sky","enemy9HP": 31879,"enemy9Class": "Lancer","enemy9Attribute": "Sky"},
{"id":76, "name": "Gilfest 2019 Rotation 3 {<a href= https://fategrandorder.fandom.com/wiki/Battle_in_New_York_2019#Tournament_Quest\" target=\"_blank\">wiki</a>}",
"enemy1HP": 20845,"enemy1Class": "Saber","enemy1Attribute": "Sky","enemy2HP": 11026,"enemy2Class": "Saber","enemy2Attribute": "Sky","enemy3HP": 11026,"enemy3Class": "Saber","enemy3Attribute": "Sky",
"enemy4HP": 24788,"enemy4Class": "Saber","enemy4Attribute": "Sky","enemy5HP": 24788,"enemy5Class": "Saber","enemy5Attribute": "Sky","enemy6HP": 65100,"enemy6Class": "Saber","enemy6Attribute": "Earth",
"enemy7HP": 140976,"enemy7Class": "Saber","enemy7Attribute": "Earth","enemy8HP": 81360,"enemy8Class": "Saber","enemy8Attribute": "Earth","enemy9HP": 76290,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":77, "name": "Gilfest 2019 Rotation 2 Ticket Node {<a href= \"https://fategrandorder.fandom.com/wiki/Battle_in_New_York_2019#Tournament_Quest\" target=\"_blank\">wiki</a>}",
"enemy1HP": 17066,"enemy1Class": "Saber","enemy1Attribute": "Sky","enemy2HP": 17066,"enemy2Class": "Saber","enemy2Attribute": "Sky","enemy3HP": 26428,"enemy3Class": "Saber","enemy3Attribute": "Sky",
"enemy4HP": 30869,"enemy4Class": "Saber","enemy4Attribute": "Sky","enemy5HP": 65660,"enemy5Class": "Saber","enemy5Attribute": "Earth","enemy6HP": 0,"enemy6Class": "Saber","enemy6Attribute": "Man",
"enemy7HP": 131923,"enemy7Class": "Saber","enemy7Attribute": "Sky","enemy8HP": 45279,"enemy8Class": "Ruler","enemy8Attribute": "Star","enemy9HP": 88469,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":78, "name": "Gilfest 2019 Rotation 1 Ticket Node {<a href= \"https://fategrandorder.fandom.com/wiki/Battle_in_New_York_2019#Tournament_Quest\" target=\"_blank\">wiki</a>}",
"enemy1HP": 18801,"enemy1Class": "Caster","enemy1Attribute": "Man","enemy2HP": 14601,"enemy2Class": "Caster","enemy2Attribute": "Man","enemy3HP": 18601,"enemy3Class": "Caster","enemy3Attribute": "Man",
"enemy4HP": 32450,"enemy4Class": "Caster","enemy4Attribute": "Man","enemy5HP": 55704,"enemy5Class": "Caster","enemy5Attribute": "Sky","enemy6HP": 31555,"enemy6Class": "Caster","enemy6Attribute": "Man",
"enemy7HP": 130702,"enemy7Class": "Caster","enemy7Attribute": "Man","enemy8HP": 67872,"enemy8Class": "Caster","enemy8Attribute": "Man","enemy9HP": 88406,"enemy9Class": "Caster","enemy9Attribute": "Man"},
{"id":79, "name": "Demonic Flame Lantern: Jō Three, Bō Three (Heian-kyō) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Heian-ky%C5%8D#J.C5.8D_Seven.2C_B.C5.8D_Four\" target=\"_blank\">wiki</a>}",
"enemy1HP": 12666,"enemy1Class": "Lancer","enemy1Attribute": "Earth","enemy2HP": 14575,"enemy2Class": "Lancer","enemy2Attribute": "Earth","enemy3HP": 17007,"enemy3Class": "Lancer","enemy3Attribute": "Earth",
"enemy4HP": 33197,"enemy4Class": "Lancer","enemy4Attribute": "Earth","enemy5HP": 29937,"enemy5Class": "Lancer","enemy5Attribute": "Earth","enemy6HP": 40354,"enemy6Class": "Lancer","enemy6Attribute": "Earth",
"enemy7HP": 113908,"enemy7Class": "Berserker","enemy7Attribute": "Earth","enemy8HP": 159135,"enemy8Class": "Berserker","enemy8Attribute": "Earth","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":80, "name": "Scales of Phantasy/Fantasies: Londinium (Avalon Le Fae) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Avalon_le_Fae#Londinium\" target=\"_blank\">wiki</a>}",
"enemy1HP": 22037,"enemy1Class": "Saber","enemy1Attribute": "Earth","enemy2HP": 20418,"enemy2Class": "Saber","enemy2Attribute": "Earth","enemy3HP": 21228,"enemy3Class": "Saber","enemy3Attribute": "Earth",
"enemy4HP": 31986,"enemy4Class": "Saber","enemy4Attribute": "Earth","enemy5HP": 33120,"enemy5Class": "Saber","enemy5Attribute": "Earth","enemy6HP": 80783,"enemy6Class": "Caster","enemy6Attribute": "Earth",
"enemy7HP": 42264,"enemy7Class": "Saber","enemy7Attribute": "Earth","enemy8HP": 97815,"enemy8Class": "Caster","enemy8Attribute": "Earth","enemy9HP": 40779,"enemy9Class": "Saber","enemy9Attribute": "Earth"},
{"id":81, "name": "Rainbow Yarn/Thread Ball: Gojō Bridge (Heian-kyō) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Heian-ky%C5%8D#Goj.C5.8D_Bridge\" target=\"_blank\">wiki</a>}",
"enemy1HP": 9345,"enemy1Class": "Lancer","enemy1Attribute": "Earth","enemy2HP": 12237,"enemy2Class": "Lancer","enemy2Attribute": "Earth","enemy3HP": 11636,"enemy3Class": "Lancer","enemy3Attribute": "Earth",
"enemy4HP": 13589,"enemy4Class": "Lancer","enemy4Attribute": "Earth","enemy5HP": 18785,"enemy5Class": "Lancer","enemy5Attribute": "Earth","enemy6HP": 17926,"enemy6Class": "Lancer","enemy6Attribute": "Earth",
"enemy7HP": 29889,"enemy7Class": "Lancer","enemy7Attribute": "Earth","enemy8HP": 153979,"enemy8Class": "Lancer","enemy8Attribute": "Earth","enemy9HP": 128277,"enemy9Class": "Lancer","enemy9Attribute": "Earth"},
{"id":82, "name": "Amnesty Bell: Misty Coast (Avalon Le Fae) {<a href= \"https://fategrandorder.fandom.com/wiki/Free_Quests:_Avalon_le_Fae#Misty_Coast\" target=\"_blank\">wiki</a>}",
"enemy1HP": 28807,"enemy1Class": "Berserker","enemy1Attribute": "Earth","enemy2HP": 26552,"enemy2Class": "Berserker","enemy2Attribute": "Earth","enemy3HP": 27664,"enemy3Class": "Berserker","enemy3Attribute": "Earth",
"enemy4HP": 31968,"enemy4Class": "Berserker","enemy4Attribute": "Earth","enemy5HP": 34609,"enemy5Class": "Berserker","enemy5Attribute": "Earth","enemy6HP": 33288,"enemy6Class": "Berserker","enemy6Attribute": "Earth",
"enemy7HP": 95610,"enemy7Class": "Berserker","enemy7Attribute": "Earth","enemy8HP": 91786,"enemy8Class": "Berserker","enemy8Attribute": "Earth","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":83, "name": "Cursed Beast Gallstone & Arrowhead of Disasterous Sin: Giant Demon Boar Hunt Quest (Hunting Quest Part VI) *Assumes Radiant Dawn Hand* {<a href= \"https://fategrandorder.fandom.com/wiki/Hunting_Quests_Part_VI#\" target=\"_blank\">wiki</a>}",
"enemy1HP": 28725,"enemy1Class": "Assassin","enemy1Attribute": "Man","enemy2HP": 34650,"enemy2Class": "Assassin","enemy2Attribute": "Man","enemy3HP": 28725,"enemy3Class": "Assassin","enemy3Attribute": "Man",
"enemy4HP": 43397,"enemy4Class": "Assassin","enemy4Attribute": "Man","enemy5HP": 60885,"enemy5Class": "Assassin","enemy5Attribute": "Man","enemy6HP": 43397,"enemy6Class": "Assassin","enemy6Attribute": "Man",
"enemy7HP": 145568,"enemy7Class": "Berserker","enemy7Attribute": "Sky","enemy8HP": 107135,"enemy8Class": "Berserker","enemy8Attribute": "Man","enemy9HP": 180345,"enemy9Class": "Berserker","enemy9Attribute": "Earth"},
{"id":84, "name": "Lamp of Evil Sealing & Mystic Gunpowder: Efreet Hunt Quest (Hunting Quest Part VI) *Assumes Radiant Dawn Hand* {<a href= \"https://fategrandorder.fandom.com/wiki/Hunting_Quests_Part_VI#\" target=\"_blank\">wiki</a>}",
"enemy1HP": 20727,"enemy1Class": "Archer","enemy1Attribute": "Man","enemy2HP": 26321,"enemy2Class": "Archer","enemy2Attribute": "Man","enemy3HP": 20727,"enemy3Class": "Archer","enemy3Attribute": "Man",
"enemy4HP": 30619,"enemy4Class": "Archer","enemy4Attribute": "Man","enemy5HP": 30619,"enemy5Class": "Archer","enemy5Attribute": "Man","enemy6HP": 38772,"enemy6Class": "Archer","enemy6Attribute": "Man",
"enemy7HP": 88060,"enemy7Class": "Caster","enemy7Attribute": "Man","enemy8HP": 163721,"enemy8Class": "Caster","enemy8Attribute": "Earth","enemy9HP": 48882,"enemy9Class": "Assassin","enemy9Attribute": "Man"},
{"id":85, "name": "Eternal Gear & Spinal Fluid: Helter Skelter Hunt Quest (Hunting Quest Part VI) *Assumes Radiant Dawn Hand* {<a href= \"https://fategrandorder.fandom.com/wiki/Hunting_Quests_Part_VI#\" target=\"_blank\">wiki</a>}",
"enemy1HP": 16420,"enemy1Class": "Rider","enemy1Attribute": "Man","enemy2HP": 39959,"enemy2Class": "Rider","enemy2Attribute": "Man","enemy3HP": 19904,"enemy3Class": "Caster","enemy3Attribute": "Man",
"enemy4HP": 39959,"enemy4Class": "Rider","enemy4Attribute": "Man","enemy5HP": 31948,"enemy5Class": "Caster","enemy5Attribute": "Man","enemy6HP": 31948,"enemy6Class": "Caster","enemy6Attribute": "Man",
"enemy7HP": 193841,"enemy7Class": "Rider","enemy7Attribute": "Man","enemy8HP": 31948,"enemy8Class": "Caster","enemy8Attribute": "Man","enemy9HP": 86263,"enemy9Class": "Rider","enemy9Attribute": "Sky"},
{"id":86, "name": "Phoenix Feathers: Amazoness Hunt Quest (Hunting Quest Part VI) *Assumes Radiant Dawn Hand* {<a href= \"https://fategrandorder.fandom.com/wiki/Hunting_Quests_Part_VI#\" target=\"_blank\">wiki</a>}",
"enemy1HP": 41941,"enemy1Class": "Archer","enemy1Attribute": "Man","enemy2HP": 45429,"enemy2Class": "Archer","enemy2Attribute": "Man","enemy3HP": 41941,"enemy3Class": "Archer","enemy3Attribute": "Man",
"enemy4HP": 53191,"enemy4Class": "Archer","enemy4Attribute": "Man","enemy5HP": 86500,"enemy5Class": "Archer","enemy5Attribute": "Man","enemy6HP": 53191,"enemy6Class": "Archer","enemy6Attribute": "Man",
"enemy7HP": 88060,"enemy7Class": "Archer","enemy7Attribute": "Sky","enemy8HP": 160713,"enemy8Class": "Archer","enemy8Attribute": "Man","enemy9HP": 55318,"enemy9Class": "Archer","enemy9Attribute": "Man"},
{"id":87, "name": "Great Knight Medal: Knight Enforcer Hunt Quest (Hunting Quest Part VI) *Assumes Radiant Dawn Hand* {<a href= \"https://fategrandorder.fandom.com/wiki/Hunting_Quests_Part_VI#\" target=\"_blank\">wiki</a>}",
"enemy1HP": 21132,"enemy1Class": "Saber","enemy1Attribute": "Man","enemy2HP": 21132,"enemy2Class": "Saber","enemy2Attribute": "Man","enemy3HP": 27788,"enemy3Class": "Saber","enemy3Attribute": "Man",
"enemy4HP": 33364,"enemy4Class": "Saber","enemy4Attribute": "Man","enemy5HP": 41370,"enemy5Class": "Saber","enemy5Attribute": "Man","enemy6HP": 33364,"enemy6Class": "Saber","enemy6Attribute": "Man",
"enemy7HP": 91654,"enemy7Class": "Lancer","enemy7Attribute": "Sky","enemy8HP": 180239,"enemy8Class": "Lancer","enemy8Attribute": "Man","enemy9HP": 46954,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":88, "name": "Evil Bone: Skeleton Hunt Quest (Hunting Quest Part VI) *Assumes Radiant Dawn Hand* {<a href= \"https://fategrandorder.fandom.com/wiki/Hunting_Quests_Part_VI#\" target=\"_blank\">wiki</a>}",
"enemy1HP": 35779,"enemy1Class": "Lancer","enemy1Attribute": "Man","enemy2HP": 35257,"enemy2Class": "Lancer","enemy2Attribute": "Man","enemy3HP": 35779,"enemy3Class": "Lancer","enemy3Attribute": "Man",
"enemy4HP": 49922,"enemy4Class": "Lancer","enemy4Attribute": "Man","enemy5HP": 51363,"enemy5Class": "Lancer","enemy5Attribute": "Man","enemy6HP": 49922,"enemy6Class": "Lancer","enemy6Attribute": "Man",
"enemy7HP": 91654,"enemy7Class": "Lancer","enemy7Attribute": "Sky","enemy8HP": 194005,"enemy8Class": "Lancer","enemy8Attribute": "Man","enemy9HP": 66604,"enemy9Class": "Lancer","enemy9Attribute": "Man"},
{"id":89,"name": "QP Daily (Extreme) {<a href= \"https://fategrandorder.fandom.com/wiki/Daily_Event_Quests:_Chaldea_Gate#Into_the_Treasure_Vault\" target=\"_blank\">wiki</a>}",
"enemy1HP": 23755,"enemy1Class": "Caster","enemy1Attribute": "Sky","enemy2HP": 24483,"enemy2Class": "Caster","enemy2Attribute": "Sky","enemy3HP": 23027,"enemy3Class": "Caster","enemy3Attribute": "Sky",
"enemy4HP": 30252,"enemy4Class": "Caster","enemy4Attribute": "Sky","enemy5HP": 31999,"enemy5Class": "Caster","enemy5Attribute": "Sky","enemy6HP": 31125,"enemy6Class": "Caster","enemy6Attribute": "Sky",
"enemy7HP": 0,"enemy7Class": "Saber","enemy7Attribute": "Man","enemy8HP": 132932,"enemy8Class": "Caster","enemy8Attribute": "Sky","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":90,"name":"Christmas 2021 90+ {<a href= \"https://apps.atlasacademy.io/db/JP/quest/94064409/1/\" target=\"_blank\">wiki</a>}",
"enemy1HP": 40625,"enemy1Class": "Assassin","enemy1Attribute": "Sky","enemy2HP": 55844,"enemy2Class": "Assassin","enemy2Attribute": "Sky","enemy3HP": 39655,"enemy3Class": "Assassin","enemy3Attribute": "Sky",
"enemy4HP": 158323,"enemy4Class": "Assassin","enemy4Attribute": "Earth","enemy5HP": 0,"enemy5Class": "Saber","enemy5Attribute": "Man","enemy6HP": 0,"enemy6Class": "Saber","enemy6Attribute": "Man",
"enemy7HP": 212256,"enemy7Class": "Assassin","enemy7Attribute": "Earth","enemy8HP": 0,"enemy8Class": "Saber","enemy8Attribute": "Man","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":91,"name":"Chaldea Faerie Knight Cup (Morgan Fest) Rotation 1 90+ {<a href= \"https://apps.atlasacademy.io/db/JP/quest/94077806/1\" target=\"_blank\">wiki</a>}",
"enemy1HP": 37989,"enemy1Class": "Rider","enemy1Attribute": "Earth","enemy2HP": 42195,"enemy2Class": "Rider","enemy2Attribute": "Earth","enemy3HP": 42195,"enemy3Class": "Rider","enemy3Attribute": "Earth",
"enemy4HP": 125765,"enemy4Class": "Rider","enemy4Attribute": "Earth","enemy5HP": 0,"enemy5Class": "Saber","enemy5Attribute": "Man","enemy6HP": 0,"enemy6Class": "Saber","enemy6Attribute": "Man",
"enemy7HP": 130153,"enemy7Class": "Saber","enemy7Attribute": "Earth","enemy8HP": 174600,"enemy8Class": "Rider","enemy8Attribute": "Earth","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":92,"name":"Chaldea Faerie Knight Cup (Morgan Fest) Rotation 1 90++ {<a href= \"https://apps.atlasacademy.io/db/JP/quest/94077807/1\" target=\"_blank\">wiki</a>}",
"enemy1HP": 68928,"enemy1Class": "Archer","enemy1Attribute": "Earth","enemy2HP": 103980,"enemy2Class": "Archer","enemy2Attribute": "Earth","enemy3HP": 105717,"enemy3Class": "Archer","enemy3Attribute": "Earth",
"enemy4HP": 202667,"enemy4Class": "Archer","enemy4Attribute": "Earth","enemy5HP": 0,"enemy5Class": "Saber","enemy5Attribute": "Man","enemy6HP": 0,"enemy6Class": "Saber","enemy6Attribute": "Man",
"enemy7HP": 242148,"enemy7Class": "Archer","enemy7Attribute": "Earth","enemy8HP": 843551,"enemy8Class": "Archer","enemy8Attribute": "Earth","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"},
{"id":93,"name":"Chaldea Faerie Knight Cup (Morgan Fest) Rotation 2 90+ {<a href= \"https://apps.atlasacademy.io/db/JP/quest/94077813/1\" target=\"_blank\">wiki</a>}",
"enemy1HP": 33290,"enemy1Class": "Rider","enemy1Attribute": "Earth","enemy2HP": 27593,"enemy2Class": "Rider","enemy2Attribute": "Earth","enemy3HP": 0,"enemy3Class": "Saber","enemy3Attribute": "Man",
"enemy4HP": 127447,"enemy4Class": "Rider","enemy4Attribute": "Earth","enemy5HP": 0,"enemy5Class": "Saber","enemy5Attribute": "Man","enemy6HP": 0,"enemy6Class": "Saber","enemy6Attribute": "Man",
"enemy7HP": 177487,"enemy7Class": "Rider","enemy7Attribute": "Earth","enemy8HP": 95693,"enemy8Class": "Foreigner","enemy8Attribute": "Beast","enemy9HP": 94323,"enemy9Class": "Assassin","enemy9Attribute": "Beast"},
{"id":94,"name":"Chaldea Faerie Knight Cup (Morgan Fest) Rotation 2 90++ {<a href= \"https://apps.atlasacademy.io/db/JP/quest/94077814/1\" target=\"_blank\">wiki</a>}",
"enemy1HP": 105684,"enemy1Class": "Saber","enemy1Attribute": "Earth","enemy2HP": 64581,"enemy2Class": "Saber","enemy2Attribute": "Earth","enemy3HP": 0,"enemy3Class": "Saber","enemy3Attribute": "Man",
"enemy4HP": 245860,"enemy4Class": "Saber","enemy4Attribute": "Earth","enemy5HP": 0,"enemy5Class": "Saber","enemy5Attribute": "Man","enemy6HP": 0,"enemy6Class": "Saber","enemy6Attribute": "Man",
"enemy7HP": 802320,"enemy7Class": "Saber","enemy7Attribute": "Star","enemy8HP": 76607,"enemy8Class": "Saber","enemy8Attribute": "Earth","enemy9HP": 235230,"enemy9Class": "Lancer","enemy9Attribute": "Earth"},
{"id":95,"name":"Chaldea Faerie Knight Cup (Morgan Fest) Rotation 3 90+ {<a href= \"https://apps.atlasacademy.io/db/JP/quest/94077820/1\" target=\"_blank\">wiki</a>}",
"enemy1HP": 80361,"enemy1Class": "Berserker","enemy1Attribute": "Earth","enemy2HP": 0,"enemy2Class": "Saber","enemy2Attribute": "Man","enemy3HP": 0,"enemy3Class": "Saber","enemy3Attribute": "Man",
"enemy4HP": 31238,"enemy4Class": "Berserker","enemy4Attribute": "Earth","enemy5HP": 31906,"enemy5Class": "Berserker","enemy5Attribute": "Earth","enemy6HP": 120126,"enemy6Class": "Berserker","enemy6Attribute": "Earth",
"enemy7HP": 122260,"enemy7Class": "Rider","enemy7Attribute": "Earth","enemy8HP": 103788,"enemy8Class": "Lancer","enemy8Attribute": "Earth","enemy9HP": 181524,"enemy9Class": "Berserker","enemy9Attribute": "Sky"},
{"id":96,"name":"Chaldea Faerie Knight Cup (Morgan Fest) Rotation 3 90++ {<a href= \"https://apps.atlasacademy.io/db/JP/quest/94077821/1\" target=\"_blank\">wiki</a>}",
"enemy1HP": 35839,"enemy1Class": "Archer","enemy1Attribute": "Earth","enemy2HP": 36531,"enemy2Class": "Archer","enemy2Attribute": "Earth","enemy3HP": 127400,"enemy3Class": "Archer","enemy3Attribute": "Man",
"enemy4HP": 235300,"enemy4Class": "Archer","enemy4Attribute": "Man","enemy5HP": 54413,"enemy5Class": "Archer","enemy5Attribute": "Sky","enemy6HP": 146979,"enemy6Class": "Archer","enemy6Attribute": "Earth",
"enemy7HP": 1021200,"enemy7Class": "Berserker","enemy7Attribute": "Man","enemy8HP": 0,"enemy8Class": "Saber","enemy8Attribute": "Man","enemy9HP": 0,"enemy9Class": "Saber","enemy9Attribute": "Man"}
]
