// {"id":2,"name":"test skill","imgURL":"/images/skills/attackup.png","npbuff":1,"npgainup":2,"attackup":3,"flatattackup": 4,"busterup":5,"artsup":6,"quickup":7,"powermod":8,"busterdefensedebuff":9,"artsdefensedebuff":10,"quickdefensedebuff":11,"npspattack":12,"defensedebuff":13}
const ServantSkillList = [
{"id":1,"name":"Zhuge Liang (Waver) S3","imgURL":"/images/skills/attackup.png","npbuff":0,"npgainup":0,"attackup":30,"flatattackup": 500,"busterup":0,"artsup":0,"quickup":0,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0},
{"id":2,"name":"Skadi S1","imgURL":"/images/skills/quickup.png","npbuff":0,"npgainup":0,"attackup":0,"flatattackup": 0,"busterup":0,"artsup":0,"quickup":50,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0},
{"id":3,"name":"Skadi S2","imgURL":"/images/skills/defensedown.png","npbuff":0,"npgainup":0,"attackup":0,"flatattackup": 0,"busterup":0,"artsup":0,"quickup":0,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":30},
{"id":4,"name":"Artoria Caster (Castoria) S1","imgURL":"/images/skills/attackup.png","npbuff":0,"npgainup":0,"attackup":20,"flatattackup": 0,"busterup":0,"artsup":0,"quickup":0,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0},
{"id":5,"name":"Artoria Caster (Castoria) S2","imgURL":"/images/skills/startnp.png","npbuff":0,"npgainup":30,"attackup":0,"flatattackup": 0,"busterup":0,"artsup":0,"quickup":0,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0},
{"id":6,"name":"Artoria Caster (Castoria) S3","imgURL":"/images/skills/artsup.png","npbuff":0,"npgainup":0,"attackup":0,"flatattackup": 0,"busterup":0,"artsup":50,"quickup":0,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0},
{"id":7,"name":"Merlin S1","imgURL":"/images/skills/attackup.png","npbuff":0,"npgainup":0,"attackup":20,"flatattackup": 0,"busterup":0,"artsup":0,"quickup":0,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0},
{"id":8,"name":"Merlin S3","imgURL":"/images/skills/busterup.png","npbuff":0,"npgainup":0,"attackup":0,"flatattackup": 0,"busterup":50,"artsup":0,"quickup":0,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0},
{"id":9,"name":"Tamamo Caster S1","imgURL":"/images/skills/npdrain.png","npbuff":30,"npgainup":0,"attackup":0,"flatattackup": 0,"busterup":0,"artsup":0,"quickup":0,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0},
{"id":10,"name":"Tamamo Caster S3","imgURL":"/images/skills/artsup.png","npbuff":0,"npgainup":0,"attackup":0,"flatattackup": 0,"busterup":0,"artsup":50,"quickup":0,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0},
{"id":11,"name":"Nero Claudius (Bride) S1","imgURL":"/images/skills/npgainup.png","npbuff":0,"npgainup":45,"attackup":0,"flatattackup": 0,"busterup":0,"artsup":0,"quickup":0,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0},
{"id":12,"name":"Nero Claudius (Bride) S2","imgURL":"/images/skills/attackup.png","npbuff":0,"npgainup":0,"attackup":40,"flatattackup": 0,"busterup":0,"artsup":0,"quickup":0,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0},
{"id":13,"name":"Lanling Wang S1","imgURL":"/images/skills/invishield.png","npbuff":0,"npgainup":0,"attackup":20,"flatattackup": 0,"busterup":0,"artsup":0,"quickup":0,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0},
{"id":14,"name":"Lanling Wang S3","imgURL":"/images/skills/artsup.png","npbuff":0,"npgainup":0,"attackup":0,"flatattackup": 0,"busterup":0,"artsup":20,"quickup":0,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0},
{"id":15,"name":"Helena S3","imgURL":"/images/skills/alltypeup.png","npbuff":0,"npgainup":0,"attackup":0,"flatattackup": 0,"busterup":20,"artsup":20,"quickup":20,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0},
{"id":16,"name":"Paracelsus S2","imgURL":"/images/skills/artsup.png","npbuff":0,"npgainup":0,"attackup":0,"flatattackup": 0,"busterup":0,"artsup":20,"quickup":0,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0},
{"id":17,"name":"Paracelsus S3","imgURL":"/images/skills/guts.png","npbuff":0,"npgainup":50,"attackup":0,"flatattackup": 0,"busterup":0,"artsup":0,"quickup":0,"powermod":0,"busterdefensedebuff":0,"artsdefensedebuff":0,"quickdefensedebuff":0,"npspattack":0,"defensedebuff":0}
]
